### ISSUE TITLE
Unable to start Bridge for Kubernetes

### ISSUE THREAD

**Issue by ddzubow** [microsoft/mindaro#108]
I am unable to complete the profile in order to start Bridge for Kubernetes.  I get an object reference error on the application URL dropdown.

![image](https://user-images.githubusercontent.com/1485351/105537455-f1ca2d80-5cbf-11eb-9368-e4d2e5a1b947.png)

If I attempt to manually put in the URL.  It doesn't seem to recognize it, as the 'OK' button does not become active. 

I've attached the logs related to the issue.
[bridge-library-2021-01-22-19-39-39-38704.txt](https://github.com/microsoft/mindaro/files/5858218/bridge-library-2021-01-22-19-39-39-38704.txt)
[bridge-mindarocli-2021-01-22-19-39-38-38704.txt](https://github.com/microsoft/mindaro/files/5858219/bridge-mindarocli-2021-01-22-19-39-38-38704.txt)

This is a critical blocking bug that is preventing me from working.

**Comment by daniv-msft** [comment]
Thank you for opening this issue, and sorry you're getting it.
To help us investigate, would it be possible for you to run with the same kubeconfig / namespace:
- kubectl get ingress -o json
- kubectl get services -o json
and send us the results at `BridgeToKubernetes@microsoft.com`?

We're looking at the code in parallel on our side to understand this issue.

Adding @pragyamehta for FYI.
@danegsta > Given that this field in the configuration modal is optional, would putting any value here (https://bing.com) unblock the customer, or is the logic different when in an error state?

**Comment by danegsta** [comment]
@daniv-msft unfortunately the current logic for enabling the save button would be blocked by the error attempting to retrieve the endpoint URLs

**Comment by ddzubow** [comment]
> * BridgeToKubernetes@microsoft.com

I've emailed you the responses to those commands.

**Comment by ddzubow** [comment]
> Thank you for opening this issue, and sorry you're getting it.
> To help us investigate, would it be possible for you to run with the same kubeconfig / namespace:
> 
> * kubectl get ingress -o json
> * kubectl get services -o json
>   and send us the results at `BridgeToKubernetes@microsoft.com`?
> 
> We're looking at the code in parallel on our side to understand this issue.
> 
> Adding @pragyamehta for FYI.
> @danegsta > Given that this field in the configuration modal is optional, would putting any value here (https://bing.com) unblock the customer, or is the logic different when in an error state?

I've emailed you the responses to those commands.

**Comment by daniv-msft** [comment]
Thanks @ddzubow! We're looking into this and will keep you updated in the next hours of when to expect a fix.

**Comment by irperez** [comment]
@daniv-msft I work with Dan.  Keep in mind that we have many namespaces.  And there are ingresses and services per namespace where ddzubow is a namespace the he is working under.  Do you want to see the ingress/services for ddzubow's namespace?

**Comment by daniv-msft** [comment]
Thanks @irperez! Yes, I just replied to Dan's email on this subject. The ingress/services for the namespace "ddzubow" is indeed what we're looking for.

**Comment by daniv-msft** [comment]
We replied by email to @ddzubow and @irperez, but providing more information here in case anyone else encounters this issue: this error is due to us not handling properly Ingress rules without a `path` field.

We're going to release a fix for this next week.
As a workaround, you can define `"path": "/"` for your Ingress rules without path.

**Comment by irperez** [comment]
@daniv-msft the work around worked.  Thanks!

**Comment by daniv-msft** [comment]
Thanks @irperez and @ddzubow! As discussed by email, we released early last week the Visual Studio update containing this fix. I'm closing this issue, but please let us know if you encounter any other problems. Thanks again for reporting this bug!
