### ISSUE TITLE
Debug fails with 'No process is associated with this object'

### ISSUE THREAD

**Issue by catnip-se** [microsoft/mindaro#122]
I have 3 services defined in the same solution and configured for BtK in the same way. For two of them debugging works fine but for the third one a 'No process is associated with this object' error is displayed after the EndpointManager is started. All three services are up and running in the cluster.

BtK version: 2.1.20210213.1

Logs
[bridge-endpointmanager-2021-02-19-10-55-07-40232.txt](https://github.com/microsoft/mindaro/files/6009529/bridge-endpointmanager-2021-02-19-10-55-07-40232.txt)
[bridge-library-2021-02-19-10-55-02-27944.txt](https://github.com/microsoft/mindaro/files/6009530/bridge-library-2021-02-19-10-55-02-27944.txt)
[bridge-mindarocli-2021-02-19-10-55-02-27944.txt](https://github.com/microsoft/mindaro/files/6009531/bridge-mindarocli-2021-02-19-10-55-02-27944.txt)
[2021-02-19T10-54-46.6317205.log](https://github.com/microsoft/mindaro/files/6009532/2021-02-19T10-54-46.6317205.log)

**Comment by amsoedal** [comment]
Hi @catnip-se,
From the CLI logs I see "Port number must be specified for service case-command.dev" as the failure reason. I will log a bug on our side to display this error message correctly!

**Comment by catnip-se** [comment]
Hi,
We usually only define a port number (80) in the Dockerfile and that is the same both for the failing service and the other services that can be debugged successfully.

**Comment by amsoedal** [comment]
Hmm, is there anything special about how you're declaring this service compared to the other two in the KubernetesLocalProcessConfig.yaml file? If it looks normal to you but you're still encountering issues, feel free to send us a copy of this file at BridgeToKubernetes@microsoft.com.

**Comment by catnip-se** [comment]
Ah, in the KubernetesLocalProcessConfig.yaml file for the failing service we had an environment variable definition 
name: XXX_SERVICE_HOST 
value: $(services:case-command.dev)
which referenced an old version of the service.

Removing that definition solved the problem!
Thanks for the help!

**Comment by amsoedal** [comment]
@catnip-se Awesome, glad you were able to get unblocked :)
