### ISSUE TITLE
B2K no longer working after upgrade to 16.9

### ISSUE THREAD

**Issue by irperez** [microsoft/mindaro#135]
**Describe the bug**
After upgrading Visual Studio to 16.9.2 and upgrading the B2K plugin my team is no longer able to connect to AKS at all.  Blocking issue!

No AKS clusters show up for me to select to.  I am logged in fine via Kubectl and able to retrieve cluster information.
![image](https://user-images.githubusercontent.com/1376080/111820021-5e743980-88b7-11eb-867c-63b174def763.png)
![image](https://user-images.githubusercontent.com/1376080/111821356-ed358600-88b8-11eb-8fcb-dd7ef3e4c359.png)
![image](https://user-images.githubusercontent.com/1376080/111821492-1b1aca80-88b9-11eb-9d7b-55fea58a8da0.png)
![image](https://user-images.githubusercontent.com/1376080/111821574-32f24e80-88b9-11eb-92a0-53645e205b92.png)
![image](https://user-images.githubusercontent.com/1376080/111821272-d42cd500-88b8-11eb-9e5d-362db78b7b71.png)

We're not aware of any AKS changes recently.
 
**Logs**
No logs generated from today.
 
**Environment Details**
Client used (VS Code/Visual Studio):
Microsoft Visual Studio Enterprise 2019
Version 16.9.2
VisualStudio.16.Release/16.9.2+31112.23
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

.ignore   1.2.77
A language service that makes it painless to handle all types of .ignore files such as .gitignore, .tfignore, etc.

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.688.6828
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2112521+5741df381174d72f08e3632bb99f52e8635b6a1a
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.688.6828
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.688.6828
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.688.6828
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Markdown Editor   1.12.253
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40218.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Process Editor   1.0
Process Editor for Microsoft Visual Studio Team Foundation Server

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NDepend.Package 2021.1.0   Build 2021.1.0.9500
NDepend 2021.1.0 package for Microsoft Visual Studio. For more information about NDepend, visit https://www.ndepend.com. Copyright © 2004–2021 ZEN PROGRAM LTD

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line   2.4.233
2.4.233

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62103.10080
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes
Client's version:

Operating System:
![image](https://user-images.githubusercontent.com/1376080/111821076-a2b40980-88b8-11eb-8632-ef9e5b36b28b.png)

**Comment by daniv-msft** [comment]
Thank you @irperez for logging this issue, and sorry for the perturbation for you and your team.

When you mention that no logs were generated for today, are you talking about the logs in `%TEMP%/Bridge to Kubernetes` or in `%temp%\Microsoft.VisualStudio.Kubernetes.Debugging`?

At first sight, I would expect this issue to be logged in `%TEMP%/Bridge to Kubernetes`.

**Comment by irperez** [comment]
Here is what I have in that folder sorted by date descending.
![image](https://user-images.githubusercontent.com/1376080/111822230-ed825100-88b9-11eb-8b5b-6f46f962ed41.png)

**Comment by irperez** [comment]
This is all I have in the %temp%\Microsoft.VisualStudio.Kubernetes.Debugging folder : 
![image](https://user-images.githubusercontent.com/1376080/111822411-23bfd080-88ba-11eb-89f8-d280decc64d7.png)

**Comment by daniv-msft** [comment]
Thanks @irperez. Could you please set the environment variable "MS_VS_AZUREDEVSPACES_TOOLS_LOGGING_ENABLED" (I know, we need to update this name :) ) to "true" and reproduce the scenario?
This will enable verbose logging in Visual Studio for our extension and should provide more logs in `%temp%\Microsoft.VisualStudio.Kubernetes.Debugging`.
In parallel, I'm reaching out to our team member working on the Visual Studio extension, as he might have more ideas on what's happening.

**Comment by danegsta** [comment]
Hi @irperez, it looks like the project is configured to use the old Dev Spaces Launch profile "Container in Kubernetes".  Can you try changing the Launch drop down to "Bridge to Kubernetes" and see if that allows you to select the AKS cluster?

**Comment by irperez** [comment]
I thought the same thing.  But "Bridge to Kubernetes" is not listed as an option after the upgrade.
![image](https://user-images.githubusercontent.com/1376080/111824851-18ba6f80-88bd-11eb-9f86-f06cac927d0d.png)

**Comment by irperez** [comment]
This is in the project's launch profile.  Does this matter?
![image](https://user-images.githubusercontent.com/1376080/111825052-6505af80-88bd-11eb-9487-5749dace1968.png)

**Comment by irperez** [comment]
Ok, I got it working.  This was weird.

After upgrading the B2K plugin was disabled.  Not sure why or how.  I'm not the only one that experienced this.  Others had to redownload the plugin altogether.  Once enabled, we're all good.
![image](https://user-images.githubusercontent.com/1376080/111826219-cbd79880-88be-11eb-9a78-ed7705521514.png)

**Comment by danegsta** [comment]
I've definitely seen scenarios where the extension config cache gets corrupted during an upgrade (leading to weird behavior like extensions not loading). Usually running the following commands from a developer command prompt has resolved similar issues:
```
devenv.exe /UpdateConfiguration
devenv.exe /ClearCache
```

Those commands make VS re-scan the extension folders and clear any dynamic component caches so that they'll be re-built the next time VS launches. It will slightly slow down the next launch of VS, but fixes many similar extension/component issues after a VS update.
