### ISSUE TITLE
Cannot install Bridge to Kubernetes in Visual Studio Enterprise 2019 Preview

### ISSUE THREAD

**Issue by Balfa** [microsoft/mindaro#138]
**Describe the bug**
Attempting to install the VSIX results in error message: "Specified method is not supported"
 
**To Reproduce**
Install
Microsoft Visual Studio Enterprise 2019 Preview Version 16.10.0 Preview 1.0 (VisualStudio.16.Preview/16.10.0-pre.1.0+31025.218)
Search VS Extensions for "Bridge to Kubernetes"
Click Download
Close Visual Studio and wait for error message to appear

**Expected behavior**
Extension installs successfully
 
**Logs**
Installation log:
[VSIXInstaller_24aa8b14-c274-426e-b9dd-778f4ad94e94.log](https://github.com/microsoft/mindaro/files/6206972/VSIXInstaller_24aa8b14-c274-426e-b9dd-778f4ad94e94.log)
 
**Environment Details**
[visual studio about.txt](https://github.com/microsoft/mindaro/files/6206984/visual.studio.about.txt)
Client used (VS Code/Visual Studio):
Microsoft Visual Studio Enterprise 2019 Preview
Client's version: Version 16.10.0 Preview 1.0 (VisualStudio.16.Preview/16.10.0-pre.1.0+31025.218)
Operating System: Windows 10 Version 1803

**Comment by rakeshvanga** [comment]
@Balfa Thanks for logging the issue. This seems to be an issue with VS's install engine. There might be an issue with your specific instance of the VS.
Can you try to repairing the VS instance? You can launch the VS installer, find the version you are running into the issue on, select the More dropdown button, then Repair.

**Comment by Balfa** [comment]
I will try that shortly, thanks. By the way I forgot to mention, it worked on a regular, non-preview version of VS 2019.

**Comment by Balfa** [comment]
Thanks @rakeshvanga, that worked 😅
