### ISSUE TITLE
JSON-RPC connection with the remote party was lost before the request could complete

### ISSUE THREAD

**Issue by creste** [microsoft/mindaro#140]
**Describe the bug**
After clicking "Bridge to Kubernetes" and selecting "Local Kube Config" for my Cluster source I see an error that says "The JSON-RPC connection with the remote party was lost before the request could complete."  When I click "Refresh", sometimes I see the error again and sometimes the error goes away but I still don't see any way to select my kubernetes cluster.
 
**To Reproduce**
Click "Bridge to Kubernetes":
![image](https://user-images.githubusercontent.com/3732172/112688134-cf36cb00-8e4e-11eb-81a7-af22e93641da.png)

This is what I see:
![image](https://user-images.githubusercontent.com/3732172/112688180-df4eaa80-8e4e-11eb-835c-5a30668da107.png)

After clicking "Refresh" I see this:
![image](https://user-images.githubusercontent.com/3732172/112688239-f42b3e00-8e4e-11eb-8da0-966ebbdd92b7.png)

 
**Logs**
[2021-03-26T20-13-01.7670592.log](https://github.com/microsoft/mindaro/files/6214152/2021-03-26T20-13-01.7670592.log)

**Environment Details**
Client used (VS Code/Visual Studio): Visual Studio 2019
     VS:      Visual Studio version --> 16.9.2
Operating System: Windows 10 Pro 10.0.19042

I'm trying to connect to a local kubernetes cluster running in minikube.  I am able to successfully connect to the cluster using kubectl.

**Additional context**
I read https://github.com/microsoft/mindaro/issues/129. I am using minikube, so I removed all "extensions" from my kubeconfig.  The problem remains.

I read https://github.com/microsoft/mindaro/issues/25#issuecomment-688641944 which indicated I should make sure nothing is listening in port 80.  I confirmed nothing is listening on port 80.  That comment also said to make sure my hosts file is writeable.  I've tried running Visual Studio as an administrator but still saw the problem.

**Comment by creste** [comment]
I fixed this problem by installing the Azure Development workload using the Visual Studio Installer.  I didn't realize that was a prerequisite to using Bridge to Kubernetes.

**Comment by daniv-msft** [comment]
Thanks @creste for logging this issue and happy that you found the solution.

@danegsta Could you please confirm this is a requirement in Visual Studio to install the Azure Development workload? I don't believe we're mentioning that in the doc, so if it is we should update that.
