### ISSUE TITLE
Enabling Local Process with Kubernetes VSCode extension breaks kubectl devicelogin authentication

### ISSUE THREAD

**Issue by markphillips100** [microsoft/mindaro#15]
**Describe the bug**
The extension changes the .kube/config auth-provider configuration when you launch VSCode with the extension enabled.  This causes a kubectl command from a terminal to require a devicelogin for every usage.  The extension appears to be removing "environment: AzurePublicCloud" from the yaml (users:name:auth-provider:config:environment value)
 
**To Reproduce**
1. Launch VSCode and enable LPK extension.
2. Close all VSCode instances.
3. Delete .kube folder from user profile so starting from a clean environment.
4. `az aks get-credentials -g <cluster-resource-group> -n <cluster-name>` to get new kube config.
5. Open User Profile .kube/config file in editor and note the "environment" variable exists.  Save this property for later.  Close editor.
6. Confirm repeated kubectl commands work with only the first requiring a device login.
7. Launch VScode.
8. Open .kube/config file in editor once again and note the "environment" variable no longer exists.
9. Repeated kubectl commands now require a device login on every attempt.
10. Close VSCode.
11. Open .kube/config file in editor again and paste the "environment" variable (from step 5) back into its previous place in the config.
12. Repeat step 6 to confirm working behaviour once again.

 
**Expected behavior**
The extension should not alter the .kube/config file

**Environment Details**
Client used (CLI/VS Code/Visual Studio):
VS Code: 1.47.3
LPK Extension: 0.1.120200803
 
Operating System:
Windows 10  V2004

**Comment by pragyamehta** [comment]
Thanks for reporting the issue! We are taking a look at it and will get back to you after our investigation!

**Comment by jon-walton** [comment]
@markphillips100 I've had the same issue. Using kubelogin was a workaround for us (although I would prefer not to because it's yet another tool in the development flow)

https://github.com/Azure/kubelogin

```bash
az aks get-credentials -g <cluster-resource-group> -n <cluster-name>
kubelogin convert-kubeconfig
```

`kubelogin convert-kubeconfig` needs to be run after every `az aks get-credentials`

**Comment by markphillips100** [comment]
@jon-walton thanks for that info.  I didn't know about this tool.

Like you I'd prefer not to use another tool but if it works I'll give it a shot till there's an extension fix.

**Comment by philon-msft** [comment]
We've updated our internal version of kubectl, which should fix this issue. Please let us know if you're still seeing problems.
