### ISSUE TITLE
Extension hangs on "Preparing to run Bridge To Kubernetes configured "

### ISSUE THREAD

**Issue by jonny-scott80** [microsoft/mindaro#153]
**Describe the bug**
When attempting to connect  in isolated mode using BtK extension. Any attempt to connect hangs at Preparing to run Bridge To Kubernetes configured as pod .... 
 
**To Reproduce**
Any attempt to start debugging a service in isolated mode .

 
**Logs**
Attach logs from the following directory:
For OSX/Linux: $TMPDIR/Bridge to Kubernetes
[Bridge To Kubernetes.zip](https://github.com/microsoft/mindaro/files/6273530/Bridge.To.Kubernetes.zip)
 
**Environment Details**
Client used (VS Code/Visual Studio):VS Code - Version: 1.55
mindaro.mindaro@1.0.120210401
Operating System: macOS 11.2

**Comment by amsoedal** [comment]
Hi @jonny-scott80, I see from the server logs that this critical error was happening on the backend: "failed calling webhook \"validate.nginx.ingress.kubernetes.io\"

I'll log a bug so the subject-matter expert on our team can take a look at this, and hopefully circle back soon with an update. 
Thanks!

**Comment by amsoedal** [comment]
Hey @jonny-scott80, my colleague had a look at the issue and she mentioned that it could be something on the cluster itself: https://github.com/kubernetes/ingress-nginx/issues/5985

Could you validate that connectivity between your kubeapi server node and ingress controller pod node is working as expected?

**Comment by jonny-scott80** [comment]
I ended up recreating the cluster. So not sure what the issue was but back working now. Thanks
