### ISSUE TITLE
Is there a workaround to working with Istio (and sidecars)?

### ISSUE THREAD

**Issue by Vaccano** [microsoft/mindaro#190]
I know that Sidecars are not supported and were on the roadmap to get added (I was sad to see it go on hold).

Since it is now on hold, I thought I would ask if there are any workarounds out there to allow Bridge to Kubernetes to work with Istio and sidecars.  I am hoping I can do some extra configuration somewhere to get around the side car and still get the debugging abilities in need inside Kubernetes.

**Comment by daniv-msft** [comment]
Thanks @Vaccano for opening this issue! Sorry we're not having a full experience with Istio, that's indeed tricky.
Tagging @lolodi who worked on this on our side (and @amsoedal who looks into customer issues this week).

If I remember correctly (@lolodi feel free to add more details), we work with Istio but only when using Bridge non-isolated (each developer in your team would need to use their own cluster or their own namespace if they use their own cluster). Your issue made me realize that our Github backlog wasn't clear about that, so I updated the corresponding task to say that "isolated" support is on hold.
Regarding other sidecars, I'm not sure and I'll let @lolodi provide more details.

**Comment by lolodi** [comment]
Hi @Vaccano,
@daniv-msft is indeed correct, we are supporting sidecars today, as long as you configure Bridge without isolation.
Please let us know if you encounter any problem with this.
Thanks, 
Lorenzo

**Comment by Vaccano** [comment]
@lolodi and @daniv-msft - Thank you for the quick answer!  I am excited to hear that I can debug (even if it is without isolation).

I will open an new issue if I have problems with that (and wait hopefully for isolation with Istio).  

Thanks again!

**Comment by daniv-msft** [comment]
Sounds good, thanks @Vaccano!
