### ISSUE TITLE
Restore job deployment - kubectl timeout after 3000ms

### ISSUE THREAD

**Issue by tigerquoll** [microsoft/mindaro#194]
**Describe the bug**
When deploying non-isolated deployment on a busy cluster we get:

Failed to deploy remote restore job for pod deployment 'test/test-pod' with error: 'kubectl' timeout after 3000ms when running --kubeconfig="/var/folders/pv/d8mtpsh9493dfrbq4p28jysr0000gn/T/tmp6ZodWz.tmp" delete job,secret -n test -l mindaro.io/instance=f38de26aa9

Is it possible to configure timeout to something other than 3 seconds?
 
**To Reproduce**
Launch on busy cluster.

 
**Expected behavior**
Option for a longer timeout
 
**Logs**
[bridge-mindarocli-2021-06-23-11-24-44-76571.txt](https://github.com/microsoft/mindaro/files/6701421/bridge-mindarocli-2021-06-23-11-24-44-76571.txt)
[bridge-library-2021-06-23-11-24-45-76571.txt](https://github.com/microsoft/mindaro/files/6701423/bridge-library-2021-06-23-11-24-45-76571.txt)
 
**Environment Details**
Client's version: mindaro.mindaro@1.0.120210615
VSCode/1.0.120210615"

Operating System: macos
 
**Additional context**
Add any other outputs from the clients or context you would like to share.

**Comment by lolodi** [comment]
Hi @tigerquoll, thanks for reporting this issue.
It makes sense to use longer timeout, I logged a work item on our board and I'll let you know here when a fix is ready.

**Comment by tigerquoll** [comment]
@lolodi thank you for your consideration. I'm eager to try out this product, but the bridge constantly times out when trying to connect to our cluster - I can see the deployment just beginning to start just before the timeout.  Any idea on timeframe at all?

**Comment by lolodi** [comment]
@tigerquoll, the new version with this fix should be completely deployed by the end of this week (July 9).

**Comment by lolodi** [comment]
@tigerquoll Also, if you'd like, you can use our staging bits that already contain the fix.
If you're willing to try beta bits of our VS Code extension, here is how you can test them:

- Uninstall the Bridge to Kubernetes extension from VS Code, and make sure you close all VS Code windows.
- Delete the Bridge to Kubernetes binaries stored in `/Users/your_username/Library/"Application Support"/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/`
Warning: if you just used Bridge in the last 15 minutes, make sure that you kill the EndpointManager process before deleting these binaries (you won't be able to delete them until this process stops using them).
- Open PowerShell and set the `BRIDGE_ENVIRONMENT` environment variable to use `staging` value: `$env:BRIDGE_ENVIRONMENT="staging"`
- Open VS Code from the PowerShell window: `code`
- Download the VSIX of our extension here: https://mindarostaging.blob.core.windows.net/vscode/LKS/mindaro-1.0.1.vsix
- In VS Code, install the VSIX: `F1 > Extensions: Install from VSIX...`
- Once the extension is installed, validate that it targets our staging environment and that the binaries are downloaded properly. You should see something like this in VS Code's status bar:
![image](https://user-images.githubusercontent.com/18540925/124658122-3e618980-de58-11eb-88a0-1c70b60828f3.png)
- Here it is! You're now running our beta bits. :)

Please note that VS Code easily loses environment variables if you open a new window, so please make sure that you can see the [STAGING] prefix in the Kubernetes status bar item before testing your application.

**Comment by tigerquoll** [comment]
@lolodi  Thank you very much for the code and the instructions. I have the bridge now successfully making connections!

**Comment by lolodi** [comment]
Excellent! You should see these changes in the normal prod version by end of week, so that you won't need to do all the procedure above. I'll go ahead and close this issue.
