### ISSUE TITLE
B2K and AKS Smart Defaults?

### ISSUE THREAD

**Issue by Eneuman** [microsoft/mindaro#210]
Hi!

What "Smart Defaults" (https://azure.microsoft.com/en-us/updates/public-preview-azure-kubernetes-service-aks-smart-defaults/?cdn=disable) does B2K support?

**Comment by lolodi** [comment]
Hi @Eneuman, 
Since Bridge doesn't require an Azure service running (compared to DevSpaces) pretty much any cluster should work fine. As long as you are able to run a 'kubectl port forward' to your cluster from your dev machine Bridge should work.

**Comment by Eneuman** [comment]
Sounds great!
