### ISSUE TITLE
Documentation is down - 404

### ISSUE THREAD

**Issue by lfshr** [microsoft/mindaro#214]
**Describe the bug**
[Documentation](https://docs.microsoft.com/en-gb/visualstudio/bridge/overview-bridge-to-kubernetes?view=vs-2019) is currently returning a 404. Didn't quite know where to open this ticket.
 
**To Reproduce**
Go to [Documentation](https://docs.microsoft.com/en-gb/visualstudio/bridge/overview-bridge-to-kubernetes?view=vs-2019) page.

 
**Expected behavior**
Documentation appears.
 
** Actual Behavior **
404

**Comment by daniv-msft** [comment]
Thank you very much for reporting this! We recently made changes to our documentation, and it looks like we didn't update existing links properly. We're working on the fix ASAP.

**Comment by daniv-msft** [comment]
Also reported as https://github.com/microsoft/mindaro/issues/215

**Comment by daniv-msft** [comment]
@lfshr The documentation is back. Thank you again for reporting this issue!

**Comment by lfshr** [comment]
No problem at all!
