### ISSUE TITLE
System.Net.Sockets not working

### ISSUE THREAD

**Issue by SteveCurran** [microsoft/mindaro#233]
**Describe the bug**
Unable to get a response from a container that uses System.Net.Sockets. I can connect and send a message from my debugging code but cannot get response. The socket container logs the connection, but nothing goes across the networkstream that we get from TcpClient.GetStream(). Does this tool support Sockets and NetworkStreams?

**Comment by rakeshvanga** [comment]
@SteveCurran Yes, the tool supports `System.Net.Sockets` and `NetworkStreams`. Can you share the logs from your dev machine?
Also, can you share more information?
 - Were able to configure Bridge to Kubernetes and start a debugging session?
 - What editor are your using VS Code or Visual Studio?
 - Can you share the output from the VS Code/VS editor?

 For logs:
For Windows: %TEMP%/Bridge to Kubernetes
For OSX/Linux: $TMPDIR/Bridge to Kubernetes
If you are a Visual Studio user,  
- Set the environment variable MS_VS_AZUREDEVSPACES_TOOLS_LOGGING_ENABLED=true
- Open Visual Studio and run your scenario
- Provide logs from: %temp%\Microsoft.VisualStudio.Kubernetes.Debugging

**Comment by SteveCurran** [comment]
@rakeshvanga thanks for the reply. Everything with the bridge works. I can connect to the socketservice and I can see in the logs of the socketservice running in AKS that the connection is made. However, when trying to read the response I get an invalid response error on the networkstream when trying to do networkstream.Read stating the connection has been closed. This seems to correspond with line 213 in the logs. I have attached the logs.

I am using VSCode on Windows 10. 

`internal static void MakeTcpRequest()
{ 
    var requestHost = "socketservice.webservice.svc.cluster.local";
    var requestPort = int.Parse(Environment.GetEnvironmentVariable("SOCKETSERVICE_SERVICE_PORT"));
    Console.WriteLine("request host: " + requestHost);
    Console.WriteLine("request port: " + requestPort);

    using (TcpClient client = new TcpClient())
    {

        if(client.ConnectAsync(requestHost, requestPort).Wait(5000))
        {
            using (NetworkStream socketStream = client.GetStream())
            {
                Utils.SendMessageToStream("hello socket", socketStream);
                Console.WriteLine("Sent request to socket...");
                
                string response = null;

                while (response == null)
                {
                    string statusString = Utils.GetDataFrame(socketStream);
                    Console.WriteLine("socket status: " + statusString);
                    Console.WriteLine("socket response: " + serverResponse);
                    response = "done";   
                }

                Console.WriteLine("response is no longer null...");
            }
        }
        else
        {
            Console.WriteLine("Failed to connect to socket. Connection timed out.");
        }                
    }

}

internal static string GetDataFrame(NetworkStream ns)
{
    var frameLengthBuffer = new byte[4];
    ns.Read(frameLengthBuffer, 0, 4);

    int dataLength = BitConverter.ToInt32(frameLengthBuffer, 0);

    var data = new byte[dataLength];

    int readBytes = 0;
    int bufferSize = 1024;

    while (readBytes < dataLength)
    {
        readBytes += ns.Read(data, readBytes, Math.Min(bufferSize, dataLength - readBytes));
    }

    return Encoding.ASCII.GetString(data);
}
[bridge-library-2021-09-27-17-18-11-11032.txt](https://github.com/microsoft/mindaro/files/7245682/bridge-library-2021-09-27-17-18-11-11032.txt)
`

**Comment by SteveCurran** [comment]
This tool does not support System.Net.Sockets NetworkStreams.

**Comment by rakeshvanga** [comment]
@SteveCurran Apologies for delayed response. Due to my vacation and other work prioritization I couldn't get to investigate this issue earlier.

Thanks for sharing the code samples and log file. 

If you see from the logs:
```
ServicePortForward: stream 48 connected.
2021-09-27T17:19:16.7616793Z | Library | TRACE | ServicePortForward: sending 42 bytes via stream 48
2021-09-27T17:19:16.8252705Z | Library | TRACE | ServicePortForward: received 163 bytes in stream 48.
2021-09-27T17:19:16.8420772Z | Library | TRACE | ServicePortForward: stream 48: StopLocal
2021-09-27T17:19:26.0140405Z | Library | TRACE | Accept 9070
2021-09-27T17:19:26.0470473Z | Library | TRACE | ServicePortForward: stream 56 connected.
2021-09-27T17:19:26.0476884Z | Library | TRACE | ServicePortForward: received 45 bytes in stream 56.
2021-09-27T17:19:26.0480640Z | Library | TRACE | ServicePortForward: stream 56 closed.
```
Bridge is able to communicate with its in-cluster service that helps in debugging. 
I looked into code and turns out we fixed this exact issue but seems like it is repro'ing again. I've re-opened the issue on our side.
Regarding the fix and releasing this issue, it might not happen in next sprint and I would update once this is fixed.

**Comment by SteveCurran** [comment]
Closing this issue. B2K does work with networkstreams and sockets. It apparently was a problem with the way the code was reading the incoming response.
