### ISSUE TITLE
Cannot launch Local Process with Kubernetes from VSCode.

### ISSUE THREAD

**Issue by lbicknese** [microsoft/mindaro#28]
Cannot launch Local Process with Kubernetes from VSCode.
 
**To Reproduce**

1. Install Local Process with Kubernetes extension in VSCode.
2. Connect remote cluster and set appropriate namespace.
3. Launch Local Process with Kubernetes from debug.
4. Setup values when prompted.
5. Click continue on prompt: "We need to update your hosts file to match your cluster's environment. Administrator permissions are required for this action."
6. Receive the following error:

```
Failed to establish a connection. Error: Failed to deploy remote restore job for pod deployment 'demo/**** with error: Operation returned an invalid status code 'UnprocessableEntity'
Failed to deploy remote restore job for pod deployment 'demo/****' with error: Operation returned an invalid status code 'UnprocessableEntity'
```

**Expected behavior**

Local code is mounted and run in debug mode.
 
**Logs**

[lpk-library-2020-09-18-18-54-50-39828.txt](https://github.com/microsoft/mindaro/files/5247669/lpk-library-2020-09-18-18-54-50-39828.txt)
[lpk-mindarocli-2020-09-18-18-54-50-39828.txt](https://github.com/microsoft/mindaro/files/5247670/lpk-mindarocli-2020-09-18-18-54-50-39828.txt)
[lpk-library-2020-09-18-18-53-50-21796.txt](https://github.com/microsoft/mindaro/files/5247671/lpk-library-2020-09-18-18-53-50-21796.txt)
[lpk-mindarocli-2020-09-18-18-53-50-21796.txt](https://github.com/microsoft/mindaro/files/5247672/lpk-mindarocli-2020-09-18-18-53-50-21796.txt)
 
**Environment Details**
Client used (VS Code/Visual Studio): 1.49.1
Client's version: mindaro.mindaro@0.1.120200825
Operating System: Windows 10 Home
 
**Additional context**
The prompt asking for permission to update the Hosts file never creates a windows authorization prompt and my hosts file is never updated.

**Comment by daniv-msft** [comment]
Thank you @lbicknese for reporting this issue, and sorry you encounter it.

According to the logs you shared, this is due to a bug on our side: your Windows username contains a space, and we're not handling this properly in this scenario. :(
I'm logging a bug on our side, and we'll work on this with a high priority.

Unfortunately, I don't have a workaround to offer in the meantime to unblock you. If you're willing to try beta bits, please feel free to send me a mail (daniv@microsoft.com) so that we can send you an update as soon as we have it.

**Comment by daniv-msft** [comment]
Hello @lbicknese,
We released a new version of our VS Code extension and binaries that should unblock you.

Could you please:
- Update to the latest version of the extension in VS Code (now called `Bridge to Kubernetes`).
- Wait for the new binaries to be downloaded (the `Kubernetes` status bar item at the bottom of VS Code showing your current namespace). They might have already been downloaded in the background if your extension was already up to date.
- If you use configured Bridge to Kubernetes to run isolated, you'll also need to update in VS Code your tasks.json to remove any space from the `isolateAs` field in the task that we created when you configured Local Process.
- Launch Bridge to Kubernetes.

Please let us know if you encounter any other issues.

**Comment by lbicknese** [comment]
It appears to have made it further this after the upgrade and removing the space in `isolateAs`. However, I am now getting the following error:

```
Failed to get routing manager deployment status
```

**Comment by daniv-msft** [comment]
Thank you for your quick reply! I'm following up with the team about this and I'll let you know if we need more information to make progress on this issue.

**Comment by amsoedal** [comment]
Hi @lbicknese do you have logs for the "Failed to get routing manager deployment status" issue? Thanks so much!

**Comment by lbicknese** [comment]
If there are more detailed logs that I can provide, let me know. However, this is what is displayed on the console:

```
> Executing task: local-process-with-kubernetes.service <

Redirecting Kubernetes service vtgservicesubmission to your machine...
Current cluster: vtg-pre-prod
Current namespace: develop
Target service name: vtgservicesubmission
Target service ports: 5002
Isolating service with routing header: LukeBic-90fc

Routing successfully enabled for service through pod 'lukebicknese-vtgservicesubmission-56d7d69f99-gcztm' in namespace 'develop'.
Pod 'lukebicknese-vtgservicesubmission-56d7d69f99-gcztm' created in namespace 'develop'.
Found container 'vtgservicesubmission' in pod 'lukebicknese-vtgservicesubmission-56d7d69f99-gcztm'.
Preparing to run Bridge To Kubernetes configured as service develop/vtgservicesubmission ...
Failed to get routing manager deployment status
Stopping workload and cleaning up...
Restore: Pod 'lukebicknese-vtgservicesubmission-56d7d69f99-gcztm' deleted.

Error: Failed to establish a connection. Error: Failed to get routing manager deployment status

The terminal process terminated with exit code: 1.
```

**Comment by amsoedal** [comment]
Ah okay! I actually meant if you could upload the log files from the temp folder, similar to how they were included in the original issue (bridge-library-..., bridge-endpointmanager-... and so on) . They should be under %TEMP%/Bridge to Kubernetes now

**Comment by amsoedal** [comment]
Hi @lbicknese , I was actually able to repro this locally--in addition to removing the space, could you also replace any uppercase letters? So sorry about the inconvenience, we're working to get these fixes into our routing-generation ASAP.

**Comment by lbicknese** [comment]
Hi @amsoedal , still got the same error message. One thing that I still notice is that I receive a prompt that say the extension needs administrator access to update my hosts file. However, I never get any UAC prompt and my hosts file is never updated.

If there is any other logging I can provide or if there are any other debugging steps I can take please let me know.

**Comment by amsoedal** [comment]
Ok thanks for confirming @lbicknese! Sounds like there is a problem with the EndpointManager launch as well. Will keep investigating

**Comment by lbicknese** [comment]
@amsoedal , sorry I forgot to add logs.

[bridge-library-2020-09-23-19-05-28-28764.txt](https://github.com/microsoft/mindaro/files/5271241/bridge-library-2020-09-23-19-05-28-28764.txt)
[bridge-mindarocli-2020-09-23-19-05-28-28764.txt](https://github.com/microsoft/mindaro/files/5271242/bridge-mindarocli-2020-09-23-19-05-28-28764.txt)
[bridge-library-2020-09-23-19-03-20-20888.txt](https://github.com/microsoft/mindaro/files/5271243/bridge-library-2020-09-23-19-03-20-20888.txt)
[bridge-mindarocli-2020-09-23-19-03-20-20888.txt](https://github.com/microsoft/mindaro/files/5271244/bridge-mindarocli-2020-09-23-19-03-20-20888.txt)
[bridge-library-2020-09-23-19-03-15-13292.txt](https://github.com/microsoft/mindaro/files/5271245/bridge-library-2020-09-23-19-03-15-13292.txt)
[bridge-mindarocli-2020-09-23-19-03-15-13292.txt](https://github.com/microsoft/mindaro/files/5271246/bridge-mindarocli-2020-09-23-19-03-15-13292.txt)

**Comment by jstaf** [comment]
I'm seeing this too - from what I can tell, the `isolateAs` functionality itself seems to be the broken part. 

```
Preparing to run Bridge To Kubernetes configured as service default/k8s-sandbox ...
Failed to get routing manager deployment status
Stopping workload and cleaning up...
Restore: Pod 'jstaf-k8s-sandbox-dddcb5c4b-qrnk4' deleted.
Failed to establish a connection. Error: Failed to get routing manager deployment status
```

Details:

OS: Linux (Pop!_OS 20.04 LTS)
VSCode version: code/stable,now 1.49.1-1600299189 amd64
Extension version: v1.0.120200919
Kubernetes versions (yes, I'm using EKS on AWS... I know this isn't exactly a supported configuration at the moment): 

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

As soon as I remove `isolateAs` from `.vscode/tasks.json` (and get rid of the isolation functionality entirely), it works just fine. The value I had for isloateAs (before I deleted it) was `jstaf-fa94`.

**Comment by daniv-msft** [comment]
Thank you @jstaf for reporting this issue. From what you mention, the root cause seems to be different as your `isolateAs` header is correct.

Would it be possible for you to reproduce the bug and send us the Bridge to Kubernetes logs? You can find them in `$TMPDIR/Bridge to Kubernetes`.
These logs might contain personally identifiable information, so if you prefer not to attach them on GitHub, you can send them to me directly: `daniv@microsoft.com`

This will help us understand what's going on and unblock you.

**Comment by jstaf** [comment]
@daniv-msft I've attached the logs here, enjoy:

[bridge-library-2020-09-25-13-35-34-56261.txt](https://github.com/microsoft/mindaro/files/5283153/bridge-library-2020-09-25-13-35-34-56261.txt)
[bridge-library-2020-09-25-13-35-37-56282.txt](https://github.com/microsoft/mindaro/files/5283154/bridge-library-2020-09-25-13-35-37-56282.txt)
[bridge-mindarocli-2020-09-25-13-35-34-56261.txt](https://github.com/microsoft/mindaro/files/5283156/bridge-mindarocli-2020-09-25-13-35-34-56261.txt)
[bridge-mindarocli-2020-09-25-13-35-36-56282.txt](https://github.com/microsoft/mindaro/files/5283157/bridge-mindarocli-2020-09-25-13-35-36-56282.txt)

**Comment by amsoedal** [comment]
Thanks for these logs @jstaf !
We hope to get a fix out for this issue in our release next week. @lbicknese do you mind confirming whether the account you're using on your machine is an admin account or not?

**Comment by lbicknese** [comment]
@amsoedal , I am on a local Administrator account.

**Comment by amsoedal** [comment]
We just released a fix this morning, please let us know if either of you still repro this issue!

**Comment by lbicknese** [comment]
It made further this time. I did receive the UAC prompt to allow EndpointManager. Logs attached:

[bridge-library-2020-09-28-18-43-41-13104.txt](https://github.com/microsoft/mindaro/files/5294394/bridge-library-2020-09-28-18-43-41-13104.txt)
[bridge-mindarocli-2020-09-28-18-43-41-13104.txt](https://github.com/microsoft/mindaro/files/5294395/bridge-mindarocli-2020-09-28-18-43-41-13104.txt)
[bridge-endpointmanager-2020-09-28-18-44-08-20288.txt](https://github.com/microsoft/mindaro/files/5294396/bridge-endpointmanager-2020-09-28-18-44-08-20288.txt)
[bridge-library-2020-09-28-18-43-36-19208.txt](https://github.com/microsoft/mindaro/files/5294397/bridge-library-2020-09-28-18-43-36-19208.txt)
[bridge-mindarocli-2020-09-28-18-43-35-19208.txt](https://github.com/microsoft/mindaro/files/5294398/bridge-mindarocli-2020-09-28-18-43-35-19208.txt)
[bridge-mindarocli-2020-09-28-14-58-53-10528.txt](https://github.com/microsoft/mindaro/files/5294399/bridge-mindarocli-2020-09-28-14-58-53-10528.txt)
[bridge-mindarocli-2020-09-28-14-14-28-17032.txt](https://github.com/microsoft/mindaro/files/5294400/bridge-mindarocli-2020-09-28-14-14-28-17032.txt)
[bridge-mindarocli-2020-09-28-13-37-06-14372.txt](https://github.com/microsoft/mindaro/files/5294401/bridge-mindarocli-2020-09-28-13-37-06-14372.txt)
[bridge-mindarocli-2020-09-28-13-26-53-9708.txt](https://github.com/microsoft/mindaro/files/5294402/bridge-mindarocli-2020-09-28-13-26-53-9708.txt)
[bridge-mindarocli-2020-09-28-13-14-54-6548.txt](https://github.com/microsoft/mindaro/files/5294403/bridge-mindarocli-2020-09-28-13-14-54-6548.txt)
[bridge-mindarocli-2020-09-28-12-45-14-6840.txt](https://github.com/microsoft/mindaro/files/5294404/bridge-mindarocli-2020-09-28-12-45-14-6840.txt)

**Comment by amsoedal** [comment]
From the logs it looks like you're still on the 1.0.20200918.12 version -- if you go to the Bridge to Kubernetes extension in VS Code, do you see an update available? Thanks for the logs btw!

**Comment by lbicknese** [comment]
@amsoedal , may have spoken too soon. After stopping and restarting the debugging process it will no longer connect.

[bridge-library-2020-09-28-20-47-20-7756.txt](https://github.com/microsoft/mindaro/files/5294978/bridge-library-2020-09-28-20-47-20-7756.txt)
[bridge-mindarocli-2020-09-28-20-47-20-7756.txt](https://github.com/microsoft/mindaro/files/5294979/bridge-mindarocli-2020-09-28-20-47-20-7756.txt)
[bridge-endpointmanager-2020-09-28-20-47-36-3168.txt](https://github.com/microsoft/mindaro/files/5294980/bridge-endpointmanager-2020-09-28-20-47-36-3168.txt)
[bridge-library-2020-09-28-20-47-16-22160.txt](https://github.com/microsoft/mindaro/files/5294981/bridge-library-2020-09-28-20-47-16-22160.txt)
[bridge-mindarocli-2020-09-28-20-47-15-22160.txt](https://github.com/microsoft/mindaro/files/5294982/bridge-mindarocli-2020-09-28-20-47-15-22160.txt)

**Comment by amsoedal** [comment]
@lbicknese  thanks for reporting this! I'll look into it. Does it repro consistently? Also I've asked my colleague to respond to your other question, I think she'll follow up here shortly

**Comment by lbicknese** [comment]
@amsoedal , I closed VS Code and tried again and it is working now. I removed the `isolateAs` property from my launch config and I now see requests being served by my local process.

I've been reading the documentation on the isolation functionality which relies on a subdomain. I am assuming that I would need to have an A record configured for the subdomain to route to my public IP if I wanted that to work.

Thanks for all your help. I think everything is working now, so I will close the issue.

**Comment by pragyamehta** [comment]
@jstaf Thanks for providing the logs. It would be great if you could attach the logs from the routing manager running in your namespace. You can retrieve the logs by running the below commands :

1. Retrieve the routing manager pod name
kubectl -n {namespace} get pods
2. Retrieve logs for the routing manager pod
kubectl -n {namespace} logs {routing manager pod name from step 1} > routing-manager-logs.txt

Kindly send the routing-manager-logs.txt to us and we will investigate and get back to you!

**Comment by jstaf** [comment]
Hey @pragyamehta sorry on the slowness (work has been a little crazy lately so I didn't have the chance to get back on this issue until now). Upon reproducing things from scratch again with the latest version of the "Bridge To Kubernetes" extension, everything works (both with and without using `isolateAs`). It looks like the fix from a week or so again did fix the issue - thanks! :slightly_smiling_face:
