### ISSUE TITLE
VS22: Wrong overload of OnBeforeLaunchAsync called

### ISSUE THREAD

**Issue by Snotax** [microsoft/mindaro#293]
**Describe the bug**
Whenever I want to start my Bridge in Visual Studio 2022, I get following popup and the debugger stops:
![image](https://user-images.githubusercontent.com/11430940/156175193-e65c0c2e-2902-43d0-88f4-a10f98c20677.png)

The Bridge still starts in the background, but you don't see it. You can then start the debugger again manually and get it to work this way. 
There are no errors in the logs of the bridge. 

The bridge also doesn't disconnect when stopping the debug process. 
Even thought following properties are set:
![image](https://user-images.githubusercontent.com/11430940/156176148-5b6e27b5-bb95-4958-911a-0096d972e425.png)

**To Reproduce**
Steps to follow to reproduce this issue.

- Use Bridge to K8s with Visual Studio 2022
- Try to debug an application with the bridge as debug option
 
 
**Environment Details**
Client used (Visual Studio):
     VS:      Visual Studio version --> 2022

Client's version:
Operating System:
 Win 11

**Comment by NCarlsonMSFT** [comment]
@Snotax What type of project are you using?
Also, can you check the value of LocalLaunchProfile in your <project name>.user file? This should be the name of another launch profile in the project that is used once the bridge is configured. That launch profile is most likely the one raising this error.

**Comment by Snotax** [comment]
@NCarlsonMSFT  Thank you for your reply. I just found out that it works with Web (API) Projects but not with simple Console Applications. I have some console applications that function as Kafka Consumers that I'd like to debug with B2K8s. 

`{
  "profiles": {
    "GT-TenantOrchestrator.Handler": {
      "commandName": "Project"
    },
    "Docker": {
      "commandName": "Docker"
    },
    "Bridge to Kubernetes": {
      "commandName": "AzureDevSpacesLocal",
      "launchBrowser": true
    }
  }
}`

I also tried changing "AzureDevSpacesLocal" to "Project", then the debugger starts, but it can't make a connection to the AKS.
And yes, all my applications worked with VS2019.

**Comment by NCarlsonMSFT** [comment]
@Snotax thanks, I've been able to reproduce the issue and have started working on a fix. We hope to be able to release it next week.

**Comment by NCarlsonMSFT** [comment]
@Snotax this should be fixed in today's release.

**Comment by Snotax** [comment]
@NCarlsonMSFT Hi, thanks for the release! After some initial tests it seems to be fixed now :D Thanks!
