### ISSUE TITLE
Question: Does bridge to kubernetes work with all kubernetes distributions?

### ISSUE THREAD

**Issue by kot-pilot** [microsoft/mindaro#311]
So the question is if this tool only supposed to work with Azure, or with any of kubernetes distros? Or maybe it's restricted to only some list of distros like: Azure, AWS, Openshift, GKE?

**Comment by daniv-msft** [comment]
Thanks for your question. Bridge to Kubernetes should work with any Kubernetes cluster (including not only Cloud hosted clusters but also local ones such as Minikube). That said, we're doing most of our testing on AKS. If you detect an issue with another cluster, please feel free to open an issue.
