### ISSUE TITLE
This action requires dependencies that are not available yet. Please look at the "Kubernetes" item in the status bar for more information.

### ISSUE THREAD

**Issue by alberthuang24** [microsoft/mindaro#319]
**Describe the bug**
My Kubernetes extension is working fine, but this error occurs, and I don't understand why because I can't see the source code

![image](https://user-images.githubusercontent.com/20190812/164387749-6a971c0b-a167-47bc-b0c6-839d9887a66c.png)

![image](https://user-images.githubusercontent.com/20190812/164387649-6cdcd389-aff9-49e9-aea0-1588977a923b.png)

 
**To Reproduce**
Steps to follow to reproduce this issue.

 
**Expected behavior**
 
**Logs**
Attach logs from the following directory:
For Windows: %TEMP%/Bridge to Kubernetes
For OSX/Linux: $TMPDIR/Bridge to Kubernetes
If you are a Visual Studio user,  
- Set the environment variable MS_VS_AZUREDEVSPACES_TOOLS_LOGGING_ENABLED=true
- Open Visual Studio and run your scenario
- Provide logs from: %temp%\Microsoft.VisualStudio.Kubernetes.Debugging
 
**Environment Details**
Client used (VS Code/Visual Studio): VS Code
 
Client's version: mindaro.mindaro@1.0.120220125
Operating System: macOS Monterey 
 
**Additional context**
Add any other outputs from the clients or context you would like to share.

**Comment by daniv-msft** [comment]
Thanks for reporting this issue. This message means that we're missing some of the dependencies we need for this feature. Either these dependencies are still downloading, or there is an error downloading them.

Could you please confirm what you see in VS Code's status bar? Do you see the Kubernetes item? Can you click on it?
![image](https://user-images.githubusercontent.com/48293037/164507199-8b27291d-d5f2-49cb-a2bd-6e27946338e2.png)

**Comment by jmclong** [comment]
I'm seeing this issue as well. The error is:

```Failed to update dependencies: The "streams" argument must be specified```

Check out some discussion about the issue in the following:
https://github.com/microsoft/mindaro/issues/32#issuecomment-1103702135

Thanks.

**Comment by daniv-msft** [comment]
Thanks, we believe we have a fix for this (in our File Downloader separate extension), and we'll push it early next week.

**Comment by alberthuang24** [comment]
Thank you very much
