### ISSUE TITLE
[help]: environment variables sync

### ISSUE THREAD

**Issue by Kiddinglife** [microsoft/mindaro#321]
Hey folks, the document says Mindoro will sync env variables from the remote pod to the local dev machine. But where are those env variables? Are they automatically injected into the local process ? Thx

**Comment by daniv-msft** [comment]
Yes, that's correct: the environment variables we retrieve from the cluster are automatically injected into the local process.
If you're using VS Code, you can see the environment variables we inject by:
* Starting to debug with Bridge.
* Clicking on the Kubernetes item in your status bar:
![image](https://user-images.githubusercontent.com/48293037/166299212-f38ab1b5-d1bb-41a7-8e8a-4b5f91b941fe.png)
* In the menu that opens, click "Show connection diagnostics information":
![image](https://user-images.githubusercontent.com/48293037/166299338-004cc04f-8551-4f29-819e-f0421a37fa92.png)
* After that, you can see the environment variables we inject by looking at the Bridge to Kubernetes output:
![image](https://user-images.githubusercontent.com/48293037/166299467-19ad7b2e-5d13-4283-9154-886a52af8df1.png)
