### ISSUE TITLE
ETA on Multi-service Support

### ISSUE THREAD

**Issue by trhumphries** [microsoft/mindaro#34]
Any idea how far out this is? Also, could I open 2 copies of VSCode and debug a different service in each one at the same time?

**Comment by daniv-msft** [comment]
@trhumphries We already provide the multi-service debugging feature as a Preview with the latest VS Code version. You just need to open the two projects you want to debug as a [multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces) and start debugging with Bridge to Kubernetes for each of them.
Of course, each project needs to be configured for Bridge beforehand.

Please let us know if you encounter any issues.

**Comment by goelhardik** [comment]
@daniv-msft Does this also work with Visual Studio? If yes, is there some documentation on how to start debugging?

**Comment by pragyamehta** [comment]
Hi @goelhardik Yes, we work with Visual Studio as well. Here's the documentation for that 
https://docs.microsoft.com/en-us/visualstudio/containers/bridge-to-kubernetes?view=vs-2019
