### ISSUE TITLE
BTK not breaking on locally running code with local Kubernetes

### ISSUE THREAD

**Issue by SteveCurran** [microsoft/mindaro#343]
**Describe the bug**
I am running k3s,traefik, vscode, btk all locally on ubuntu 20.04. Everything works except btk. The endpointmanager has no problems connecting and running the job/replicaset to the service/pod I am debugging. I then try to access the service/pod from another service/pod unfortunately, btk never hits the breakpoint. There is no error in the frontend service/pod and the request goes through as if btk is not forwarding the requests to vscode. I do see the following in the logs:
 **"Event: LocalEnvironmentManager-StartReversePortForwarding <json>{"properties":{"result":"Failed"},"metrics":{"durationInMs":2.0}}</json>"**
 
**To Reproduce**
Same as above

 
**Expected behavior**
Does btk work with locally running kubernetes?
 
**Logs**

 csprepo is the pod in question
[btklog.txt](https://github.com/microsoft/mindaro/files/9338541/btklog.txt)

**Environment Details**
Client used VSCode
mindaro:1.0.120220811
Dotnet core / OmniSharp
Operating System: Ubuntu 20.04

**Comment by hsubramanianaks** [comment]
@SteveCurran was this working before with older version of B2K?

**Comment by hsubramanianaks** [comment]
@SteveCurran, I tested with k3s, vscode, it worked for me B2K hit my local debug point with sample todo-app. Are you trying two different things 1. local debug 2. service/pod to service/pod? Please confirm. Thank you

**Comment by SteveCurran** [comment]
@hsubramanianaks I can step into the code when just testing the front end pod. However, I am using built in traefik loadbalancer the front end uses port 7210. When running btk the local code listens on 7241. Normally, I can just navigate the front end using 7210 and btk redirects to 7241 and I can hit the break point. Unfortunately, I can only hit my local code using localhost:7241. When trying to hit another service/pod from the front end with the local service listening on 7241 the request never gets redirected.

**Comment by SteveCurran** [comment]
@hsubramanianaks I tested today with the 8/16/22 update and everything works. Not sure that was it. It may have been the wrong break points. Either way I am very happy it works with local k3s. I love this tool. Thanks for looking into this for me.
