### ISSUE TITLE
Fails to start debugging service deployed as StatefulSet, fails with error 'UnprocessableEntity'

### ISSUE THREAD

**Issue by catnip-se** [microsoft/mindaro#39]
**Describe the bug**
When starting debugging using Bridge to Kubernetes on a service deployed as a StatefulSet, the session fails with the message 

'Patch 'ns/service-0/service' to use 
'mindora.azurecr.io/lpkremoteagent:0.1.4' faliled with error: 
Operation returned an invalid status code
'UnprocessableEntity'
 
**To Reproduce**
Deploy a service as a StatefulSet and try to debug using Bridge to Kubernetes

 
**Expected behavior**
Debugging session should start
 
**Logs**
[bridge-mindarocli-2020-09-29-10-24-14-39464.txt](https://github.com/microsoft/mindaro/files/5298258/bridge-mindarocli-2020-09-29-10-24-14-39464.txt)
[bridge-library-2020-09-29-10-24-19-34496.txt](https://github.com/microsoft/mindaro/files/5298259/bridge-library-2020-09-29-10-24-19-34496.txt)
[bridge-mindarocli-2020-09-29-10-24-19-34496.txt](https://github.com/microsoft/mindaro/files/5298260/bridge-mindarocli-2020-09-29-10-24-19-34496.txt)
[bridge-library-2020-09-29-10-24-15-39464.txt](https://github.com/microsoft/mindaro/files/5298261/bridge-library-2020-09-29-10-24-15-39464.txt)

 
**Environment Details**
Client used Visual Studio:
VS:      Visual Studio version --> 16.7.3
Client's version:
Operating System: Windows 10

**Comment by amsoedal** [comment]
Hi @catnip-se , thanks for reporting this issue! I've logged a bug on our side for us to investigate.  Will update this thread when we get to the bottom of this.

**Comment by amsoedal** [comment]
Hi @catnip-se, is this a Dev Spaces enabled cluster? We generally don't recommend using Bridge and Dev Spaces together. Let me know if getting rid of the controller or testing on a fresh cluster helps you get further.  I'm sorry if our documentation wasn't clear enough on this point, I've made a note to update it.

**Comment by catnip-se** [comment]
Hi, it used to be a Dev Spaces enabled cluster but we disabled it before running Bridge. We did not create a fresh cluster or redeploy the application. We will try that.

**Comment by amsoedal** [comment]
@catnip-se Great, let us know if it works for you!

**Comment by catnip-se** [comment]
Redeploying the application did not solve the problem. However, changing from StatefulSet to Deployment made it work. This workaround will be ok for us at the moment, even though we would like this to work for StatefulSets too.  We have not yet tested with a fresh cluster to see whether that completely solves the problem.

**Comment by amsoedal** [comment]
Hi @catnip-se, glad you were able to get unblocked. I've added supporting StatefulSets to our backlog!

**Comment by ghostcoach** [comment]
@amsoedal Is there any update on this feature? We also would like to use bridge to kubernetes against StatefulSets. 

Thanks!

**Comment by daniv-msft** [comment]
Thanks @ghostcoach for your message! This feature is not available yet, but we included supporting it as part of our current sprint. If everything goes as planned, we should have more news to share at the end of March/beginning of April. :)
