### ISSUE TITLE
Ingress not duplicated and replicated Service doesn't have Annotations

### ISSUE THREAD

**Issue by trhumphries** [microsoft/mindaro#40]
**Describe the bug**
According to https://docs.microsoft.com/en-us/visualstudio/containers/overview-bridge-to-kubernetes?view=vs-2019#diagnostics-and-logging my ingress should be duplicated and there should be annotations on the duplicated services routing.visualstudio.io/route-on-header neither of these is being generated. I'm also unsure as to what DNS name I should be using to access the cluster for the routing to happen
 
**To Reproduce**
I followed the steps as outlined on the web site

**Comment by pragyamehta** [comment]
Hi @trhumphries Thanks for reaching out! Are you using our VSCode or Visual studio experience?
If you are using our Visual Studio experience, there is a checkbox that needs to be checked called "Isolate your local version of your service from other developers". This will populate the dropdown with the DNS name that will be generated for you (your ingress name prefixed with a header). Once you select the required ingress and start debugging, you should see the required resources.
We have a similar option in VS Code during configuration, and the prefixed ingresses are visible when the status bar at the bottom is clicked once debugging starts.

Let me know if the steps I have mentioned match with your repro steps and you are still facing issues. If that is the case, please provide us with Bridge to Kubernetes logs in the temp directory on your computer.

**Comment by trhumphries** [comment]
I'm using VSCode on my Mac. I can bring up the Bridge to Kubernetes and show the diagnostics. however that's not showing me the dns name is should be using. can you be a bit more specific.

Maybe it has something todo with the Local DNS service is not running. in the diagnostics log

Local service IPs:
Local DNS service is not running.
Environment variables:
KUBERNETES_PORT_443_TCP_PROTO=TCP
KUBERNETES_PORT_443_TCP_ADDR=ks-gtp-ci-dns-ttg9aa3g908c.hcp.centralus.azmk8s.io
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_HOST=ks-gtp-ci-dns-ttg9aa39g08c.hcp.centralus.azmk8s.io
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP=TCP://ks-gtp-ci-dns-ttg9aa39h08c.hcp.centralus.azmk8s.io:443
KUBERNETES_PORT=TCP://ks-gtp-ci-dns-ttg9aa390g8c.hcp.centralus.azmk8s.io:443
ASPNETCORE_ENVIRONMENT=CI
VERSION=1.2.129
PRODUCT_API_PORT=TCP://127.1.1.1:80
PRODUCT_API_SERVICE_PORT_TCP=80
PRODUCT_API_PORT_80_TCP_PROTO=TCP
PRODUCT_API_PORT_80_TCP=TCP://127.1.1.1:80
PRODUCT_API_PORT_80_TCP_PORT=80
PRODUCT_API_SERVICE_PORT=80
PRODUCT_API_PORT_80_TCP_ADDR=127.1.1.1
PRODUCT_API_SERVICE_HOST=127.1.1.1
PRODUCT_API_CLONED_ROUTING_SVC_PORT=TCP://127.1.1.2:80
PRODUCT_API_CLONED_ROUTING_SVC_SERVICE_PORT_TCP=80
PRODUCT_API_CLONED_ROUTING_SVC_PORT_80_TCP_PROTO=TCP
PRODUCT_API_CLONED_ROUTING_SVC_PORT_80_TCP=TCP://127.1.1.2:80
PRODUCT_API_CLONED_ROUTING_SVC_PORT_80_TCP_PORT=80
PRODUCT_API_CLONED_ROUTING_SVC_SERVICE_PORT=80
PRODUCT_API_CLONED_ROUTING_SVC_PORT_80_TCP_ADDR=127.1.1.2
PRODUCT_API_CLONED_ROUTING_SVC_SERVICE_HOST=127.1.1.2
PRODUCT_API_HEALTHCHECK_PORT=TCP://127.1.1.3:80
PRODUCT_API_HEALTHCHECK_SERVICE_PORT_TCP=80
PRODUCT_API_HEALTHCHECK_PORT_80_TCP_PROTO=TCP
PRODUCT_API_HEALTHCHECK_PORT_80_TCP=TCP://127.1.1.3:80
PRODUCT_API_HEALTHCHECK_PORT_80_TCP_PORT=80
PRODUCT_API_HEALTHCHECK_SERVICE_PORT=80
PRODUCT_API_HEALTHCHECK_PORT_80_TCP_ADDR=127.1.1.3
PRODUCT_API_HEALTHCHECK_SERVICE_HOST=127.1.1.3
ROUTINGMANAGER_SERVICE_PORT=TCP://127.1.1.4:80
ROUTINGMANAGER_SERVICE_SERVICE_PORT_TCP=80
ROUTINGMANAGER_SERVICE_PORT_80_TCP_PROTO=TCP
ROUTINGMANAGER_SERVICE_PORT_80_TCP=TCP://127.1.1.4:80
ROUTINGMANAGER_SERVICE_PORT_80_TCP_PORT=80
ROUTINGMANAGER_SERVICE_SERVICE_PORT=80
ROUTINGMANAGER_SERVICE_PORT_80_TCP_ADDR=127.1.1.4
ROUTINGMANAGER_SERVICE_SERVICE_HOST=127.1.1.4
SUPPLIER_API_PORT=TCP://127.1.1.5:80
SUPPLIER_API_SERVICE_PORT_TCP=80
SUPPLIER_API_PORT_80_TCP_PROTO=TCP
SUPPLIER_API_PORT_80_TCP=TCP://127.1.1.5:80
SUPPLIER_API_PORT_80_TCP_PORT=80
SUPPLIER_API_SERVICE_PORT=80
SUPPLIER_API_PORT_80_TCP_ADDR=127.1.1.5
SUPPLIER_API_SERVICE_HOST=127.1.1.5
SUPPLIER_API_CLONED_ROUTING_SVC_PORT=TCP://127.1.1.6:80
SUPPLIER_API_CLONED_ROUTING_SVC_SERVICE_PORT_TCP=80
SUPPLIER_API_CLONED_ROUTING_SVC_PORT_80_TCP_PROTO=TCP
SUPPLIER_API_CLONED_ROUTING_SVC_PORT_80_TCP=TCP://127.1.1.6:80
SUPPLIER_API_CLONED_ROUTING_SVC_PORT_80_TCP_PORT=80
SUPPLIER_API_CLONED_ROUTING_SVC_SERVICE_PORT=80
SUPPLIER_API_CLONED_ROUTING_SVC_PORT_80_TCP_ADDR=127.1.1.6
SUPPLIER_API_CLONED_ROUTING_SVC_SERVICE_HOST=127.1.1.6
SUPPLIER_API_HEALTHCHECK_PORT=TCP://127.1.1.7:80
SUPPLIER_API_HEALTHCHECK_SERVICE_PORT_TCP=80
SUPPLIER_API_HEALTHCHECK_PORT_80_TCP_PROTO=TCP
SUPPLIER_API_HEALTHCHECK_PORT_80_TCP=TCP://127.1.1.7:80
SUPPLIER_API_HEALTHCHECK_PORT_80_TCP_PORT=80
SUPPLIER_API_HEALTHCHECK_SERVICE_PORT=80
SUPPLIER_API_HEALTHCHECK_PORT_80_TCP_ADDR=127.1.1.7
SUPPLIER_API_HEALTHCHECK_SERVICE_HOST=127.1.1.7
KUBERNETES_SERVICE_PORT_TCP=443

**Comment by pragyamehta** [comment]
Hi @trhumphries Now that I know you are on VS Code on mac, I can be more specific in guiding you :)
I apologize that the experience is not working for you as expected, but I am confident we will get you unblocked.
Can you provide the logs from '$TMPDIR/Bridge To Kubernetes' folder to investigate this further?
You can email them to me at pragme@microsoft.com if you'd like.
Thanks for your patience!

**Comment by trhumphries** [comment]
I sent the logs file in a private email

**Comment by pragyamehta** [comment]
Closing this thread as we got you unblocked over email. Thanks for reaching out!
