### ISSUE TITLE
Visual Studio Bridge to gateway service hangs in the BikeSharingApp sample

### ISSUE THREAD

**Issue by goelhardik** [microsoft/mindaro#43]
**Describe the bug**
Visual Studio's `Bridge to Kubernetes` hangs on "Connecting to service ..." when trying to connect to `gateway` service in the `BikeSharingApp` sample.
 
**To Reproduce**
Open `samples/BikeSharingApp/Gateway/app.csproj` in Visual Studio and launch with the `Bridge to Kubernetes` profile.

 
**Expected behavior**
The VS instance should start a debugging session with the `gateway` service in AKS, just like how it works for the `ReservationEngine`.
  
**Environment Details**
Client used (VS Code/Visual Studio):
VS:      16.7.5
Operating System: Windows 10
 
**Question**
Does the `gateway` service need any additional configuration to be debug-able?

**Comment by pragyamehta** [comment]
Hi @goelhardik  Thanks for reaching out to us! Can you please provide the logs from the below location:

For Windows: %TEMP%/Bridge to Kubernetes
For OSX/Linux: $TMPDIR/Bridge to Kubernetes

To answer your question, no, gateway should not need any additional configuration.

**Comment by goelhardik** [comment]
Hi @pragyamehta Thanks for responding! Here are all the log files from that location. 
I first successfully connected to `ReservationEngine` and then tried connecting to `Gateway` at which point VS just kept on  "Connecting to service ..." until I cancelled manually.

[bridge-library-2020-10-02-19-34-56-32264.txt](https://github.com/microsoft/mindaro/files/5319939/bridge-library-2020-10-02-19-34-56-32264.txt)
[bridge-mindarocli-2020-10-02-19-34-55-32264.txt](https://github.com/microsoft/mindaro/files/5319940/bridge-mindarocli-2020-10-02-19-34-55-32264.txt)
[bridge-library-2020-10-02-19-35-00-56368.txt](https://github.com/microsoft/mindaro/files/5319941/bridge-library-2020-10-02-19-35-00-56368.txt)
[bridge-mindarocli-2020-10-02-19-35-00-56368.txt](https://github.com/microsoft/mindaro/files/5319942/bridge-mindarocli-2020-10-02-19-35-00-56368.txt)

**Comment by pragyamehta** [comment]
@goelhardik Thanks for providing the logs. Let me take a look and get back to you.

**Comment by pragyamehta** [comment]
Closing this thread since we got the customer unblocked offline and the issue went away on retry.
