### ISSUE TITLE
No longer able to run Bridge to Kubernetes due to bridgetokubernetes.azurecr.io images requiring authentication

### ISSUE THREAD

**Issue by jamyc** [microsoft/mindaro#45]
**Describe the bug**
Suddenly not able to run Bridge to Kubernetes anymore due to `bridgetokubernetes.azurecr.io` images (lpkrestorationjob and lpkremoteagent) requiring authentication. This was working fine a few days ago.

k get pods
```
bikes-67c9756cf9-shkdm                  1/1     Running            0          87m
bikes-778c6d986c-4fg5r                  0/1     ImagePullBackOff   0          23s
bikes-restore-93253-zgz2x               0/1     ImagePullBackOff   0          14s
```

k describe pod bikes-778c6d986c-4fg5r
```
 Failed to pull image "bridgetokubernetes.azurecr.io/lpkremoteagent:0.1.4": [rpc error: code = Unknown desc = Error response from daemon: Get https://bridgetokubernetes.azurecr.io/v2/lpkremoteagent/manifests/0.1.4: unauthorized: Application not registered with AAD., rpc error: code = Unknown desc = Error response from daemon: Get https://bridgetokubernetes.azurecr.io/v2/lpkremoteagent/manifests/0.1.4: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.]
```
 
**To Reproduce**
Run the included `Launch via NPM with Kubernetes` launch configuration that is included in the `Bikes` project.

**Comment by riker09** [comment]
Yup, this is exactly the same issue I'm getting. If you need additional information just give me a ping.

**Comment by greenie-msft** [comment]
@riker09 , @jamyc  - Thank you for bringing this issue to our attention. We have released a fix for the "Failed to pull image" issue. Please let me know if you encounter any other problems.

Thank you.

**Comment by jamyc** [comment]
Can confirm that it's working again, thanks!
