### ISSUE TITLE
Inifinite credentials prompt on initial configuration dialog

### ISSUE THREAD

**Issue by starkmsu** [microsoft/mindaro#46]
VS 2019 (Version 16.7.5) is asking me to reneter my azure account credentials in infinite loop during initial configuration - subscription, etc.
I have access to multiple subscription and at least one of them has a running Kubernetes service.
What could be the issue here?

**Comment by greenie-msft** [comment]
Hi @starkmsu,

I suspect the issue you are encountering stems from outside Bridge to Kubernetes. Bridge relies on the standard VS control for authentication. 

A couple things to try to help troubleshoot:
- Restart Visual Studio
- Sign out and sign back into the account in VS

If the options above do not resolve the issue, can you attach your extension logs (%temp%\Microsoft.VisualStudio.Kubernetes.Debugging)? We can take a look and see if there is an auth exception happening.

Thanks.

**Comment by greenie-msft** [comment]
Hi @starkmsu 

We have confirmed this is not an issue on the Bridge side.  Recommended guidance is to switch to system web browser to avoid the looping. 

Below are additional details. 
[Use accounts that require multi-factor authentication - Visual Studio | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/ide/work-with-multi-factor-authentication?view=vs-2019#using-visual-studio-with-mfa-policies) 

Please feel free to open a new issue if you still experience this behavior. Thank you.
