### ISSUE TITLE
HTTPS support for isolation mode

### ISSUE THREAD

**Issue by trhumphries** [microsoft/mindaro#51]
**Describe the bug**
When using https and isolation mode traffic is not routed to the local service being debugged
 
**To Reproduce**
Set your ingress to use https and config B2K to use isolation mode

**Comment by greenie-msft** [comment]
Hi @trhumphries,

Thanks for opening this issue.

HTTPS with isolation is not currently supported in the current Bridge experience, but it's something we are tracking and hope to address in the near future. I'm happy to update the thread as soon as I have an update to share. 

Thank you

**Comment by pragyamehta** [comment]
Hi @trhumphries We are looking at adding https support to isolated scenarios at this time and would love to chat with you regarding what solution you use for setting up certificates for https - do you use self-managed certs or an ACME solution like cert-manager with letsencrypt? Would love to hear about your setup - please feel free to email me at pragme@microsoft.com.
This will help prioritize an implementation that would work for you. Thanks!

**Comment by greenie-msft** [comment]
Closing this thread since we now support HTTPS in all work modes. 

Thank you.
