### ISSUE TITLE
Sidecar support

### ISSUE THREAD

**Issue by clintsinger** [microsoft/mindaro#52]
**Is your feature request related to a problem? Please describe.** 
I would like to be able to use Bridge To Kubernetes along with Dapr.

**Describe the solution you'd like**
Bridge to Kubernetes needs to support Pods that have Sidecars
 
**Describe alternatives you've considered**
Not using Bridge to Kubernetes could be an option but it is less awesome.

**Comment by greenie-msft** [comment]
Hi @clintsinger 

Thank you for your request.

I do not have an official date for when this will be supported, but sidecar support is something we find valuable for compatibility with many different technologies. We're tracking this closely and I hope to have an update in the near future. 

Thank you.

**Comment by abvaden** [comment]
I have this same issue as well when using Bridge with WSL. A good alternative when working with WSL is to use [telepresence](https://www.telepresence.io/) even though it has limitations in WSL as well it has allowed me to continue my work with only minor modifications to my debugging setup.

I have also experimented with using Bridge and VisualStudio Online / Codespaces and encounter the same issue.

**Comment by greenie-msft** [comment]
Hi @abvaden,

We have investigating support for these environments (respectively) on our backlog. I'm closing this thread for now, but will make an announcement once we an update to share. 

Thank you.
