### ISSUE TITLE
Support for Windows Node placement?

### ISSUE THREAD

**Issue by ChocoMachine** [microsoft/mindaro#53]
I'm not sure, and can't find this documented anywhere... Does Bridge to Kubernetes support windows nodes?

I am getting the following when trying to use with a windows container image.

Failed to pull image "bridgetokubernetes.azurecr.io/lpkrestorationjob:0.1.1": rpc error: code = Unknown desc = image operating system "linux" cannot be used on this platform

I can't seem to find anywhere to specify node placement?

**Comment by pragyamehta** [comment]
Hi @ChocoMachine We do not support windows nodes as of today, but we do plan to support it in the near future. I am happy to update this thread once we start supporting this. Meanwhile, I would encourage you to try our product with linux containers.
Thanks!
