### ISSUE TITLE
Kubernetes RBAC policy recommendations

### ISSUE THREAD

**Issue by arbielsk** [microsoft/mindaro#58]
**Is your feature request related to a problem? Please describe.** 
While we are only planning to use Bridge-To-Kubernetes on our DEV cluster, we still like to make sure that we give everyone involved only the minimal necessary rights. In order to do that we'd like to know what the minimum rights needed to use Bridge-To-Kubernetes are.
 
**Describe the solution you'd like**
I'd love to have a simple **role.yaml** file that includes the minimum rights needed to use Bridge-To-Kubernetes as a developer. 
 
**Describe alternatives you've considered**
I'm unsure if there is another more straight forward way to do this.
 
**Additional context**
Necessary rights I have identified so far:
CREATE role
CREATE rolebinding
CREATE service
CREATE deployment
CREATE service-account

If there are other best practices to consider when using Bridge-To-Kubernetes I'd highly appreciate having them documented somewhere as well :)

Thank you for considering my request!

**Comment by greenie-msft** [comment]
Hi @arbielsk 

Thank you for the feature recommendation. I will discuss your suggestion with the larger team and update the thread accordingly.

In the meantime, we are in the process of publishing the minimum permissions needed to use Bridge to Kubernetes in our documentation. I will update this thread once the docs go live. Thank you.

**Comment by arbielsk** [comment]
Thank you for your reply, @greenie-msft !

We really appreciate your hard work and the awesome developer experience that you are creating with this product!

**Comment by Alexander-Krause** [comment]
@greenie-msft Can you now provide more infos?

**Comment by greenie-msft** [comment]
Hi @arbielsk and @Alexander-Krause 

Apologies for the delay, we've recently published the doc that explains the necessary permissions required to use Bridge. We have also supplied a RoleBinding yaml as requested: 

https://docs.microsoft.com/en-us/visualstudio/containers/overview-bridge-to-kubernetes?view=vs-2019#rbac-authorization

Please let me know if you have any further questions. Thank you.

**Comment by greenie-msft** [comment]
Closing this issue for now as we have provided the necessary guidance. Please feel free to leave a comment if there are any outstanding questions. Thank you.
