### ISSUE TITLE
Do not require access to port 80 on Windows

### ISSUE THREAD

**Issue by arbielsk** [microsoft/mindaro#62]
**Is your feature request related to a problem? Please describe.** 
We are currently exploring Bridge To Kubernetes for our dev team which are both Mac and Windows users.
Mac users are having a blast as everything is working out of the box. 
On Windows we do have an enterprise policy which is being enforced and reserves port 80 for a Windows 10 Service (BranchCache). Since Bridge-To-Kubernetes currently requires access to port 80 to work on **Windows** this is blocking us from adopting the technology for our team (Mac doesn't seem to have this limitation).
 
**Describe the solution you'd like**
We'd like to have the requirement lifted to have port 80 available on Windows.
 
**Describe alternatives you've considered**
The possibility to configure an alternative port that is used instead of port 80 would be great as well.
We would also be willing to live with workarounds for now.

Thank you for considering our request!

**Comment by pragyamehta** [comment]
Hi @arbielsk, the reason we ask for port 80 access is because your app is configured such that it needs port 80 to run locally on your machine. If you are uncomfortable with freeing up port 80 on your machine, I would suggest making a change in your microservice application to run on a different port than 80 locally and also please configure Bridge to Kubernetes with this port as well. Once you do this, you will not be asked to free port 80 on Windows.
Please try this and let us know if this unblocks you. Thanks!

**Comment by pragyamehta** [comment]
You can refer to this sample microservice that runs on port 3000 locally, but port 80 in Kubernetes.
https://github.com/microsoft/mindaro/blob/master/samples/BikeSharingApp/Bikes/server.js

**Comment by arbielsk** [comment]
Hi @pragyamehta! 

Thank you very much for your reply, and please excuse my late response due to time zone differences.

I believe the information I provided in my initial request was not sufficient to describe the problem properly and to allow for a valid conclusion to my issue.

I had already investigated if anything in my setup was using port 80 beforehand and that is not the case. Please find a schematic view of my test setup below (local process port is 8080):
![image](https://user-images.githubusercontent.com/39697028/96828605-3e3f6c00-1438-11eb-941f-52c84438870b.png)

On Mac OSX the output of successfully starting Bridge-To-Kubernetes is as follows:

```
Redirecting Kubernetes service template-service to your machine...
Current cluster: xxxxxxxx-cluster
Current namespace: btk-test
Target service name: template-service
Target service ports: 8080
Isolating service with routing header: arbielsk

Loaded Bridge To Kubernetes environment file 'KubernetesLocalProcessConfig.yaml'.
Routing successfully enabled for service through pod 'arbielsk-template-service-8559967556-vx6xv' in namespace 'btk-test'.
Pod 'arbielsk-template-service-8559967556-vx6xv' created in namespace 'btk-test'.
Found container 'template-service' in pod 'arbielsk-template-service-8559967556-vx6xv'.
Preparing to run Bridge To Kubernetes configured as service btk-test/template-service ...
Connection established.
Service 'database' is available on 127.1.1.7:5432.
Service 'product-service' is available on 127.1.1.8:8081.
Service 'routingmanager-service' is available on 127.1.1.9:80.
Service 'template-service' is available on 127.1.1.10:8080.
Service 'kubernetes' is available on 127.1.1.11:443.
Hosts file updated.
Container port 8080 is available at localhost:8080.
##################### Environment started. #############################################################

The line `Service 'routingmanager-service' is available on 127.1.1.9:80.` might indicate that the routingmanager-service is requiring port 80 (if the setup on Windows is similar). Is this a valid assumption?

I have also tried to find a way to replace the port in the routing-manager, but was not able to find a solution that would apply different ports when starting up the bridge-to-kubernetes setup.

I would really appreciate a response and if you concur with my findings that you reopen the issue. If there is any other information that would be helpful I'm more than happy to provide it!

Thank you very much for your time and patience!

**Comment by pragyamehta** [comment]
Hi @arbielsk , thanks for reaching out to provide more information here!
I think I have a better understanding of the issue now, I have logged a bug on our side and we will roll out the fix in the next release. Thanks for reporting this issue!

**Comment by arbielsk** [comment]
@pragyamehta thank you so much for your feedback. 

**I have sent the requested logs to the mentioned email address as requested - if it has not arrived please let me know!**

Our team is really appreciates how responsive and helpful you and your colleagues are when it comes to this product! We are absolutely stoked to see a fix in the next release as this will unblock our devs on Windows and allow us to have a much more efficient and productive developer workflow. 
**Are you able to share a timeline or at least a guesstimate when the next release is supposed to happen?**

Thanks again for your time and effort!

**Comment by pragyamehta** [comment]
Hi @arbielsk We will be releasing the fix at the end of this week or early next week. 
We have received the logs for the other error from you and are investigating. Thanks!

**Comment by arbielsk** [comment]
@pragyamehta We have retested with the B2K VSCode extension updated on 19/11/2020, 00:30:59.

It seems the issue is now fixed. So from our perspective the issue can be closed.

Thank you very much for your hard work, our team is excited to have B2K as an additional tool in our development toolbox.

**Comment by pragyamehta** [comment]
Happy to hear that @arbielsk ! Please feel to reach out again in the future. Closing this issue as resolved.

**Comment by arbielsk** [comment]
@pragyamehta 
Unfortunately I need to correct the result of my initial testing evaluation. It seems like my initial tests falsely stated that the issue was fixed, because the program that allocated port 80 on the machine we tested on was not allocating the port at the time of the test.

There still seems to be the need for having port 80 available when starting B2K in VSCode (popup explicitly demands it and B2K fails).

Could you please confirm that this was actually fixed according to your knowledge and if not, could you please reopen the issue or let me know how to continue with this topic? 

Thanks in advance!

**Comment by pragyamehta** [comment]
Hi @arbielsk I am sorry to hear that this didn't work for you. We will be releasing a fix for this early next year.

**Comment by arbielsk** [comment]
@pragyamehta Thank you so much, I appreciate it!
