### ISSUE TITLE
Is possible to use another cloud provider?

### ISSUE THREAD

**Issue by thalesfsp** [microsoft/mindaro#67]
Need to use Azure or Google Cloud/AWS is supported for the PR integration?

**Comment by greenie-msft** [comment]
Hi @thalesfsp 

Thank you for your question. The PR Flow can be used on any Kubernetes, not just AKS. 

Our examples are for Azure, but you can author a GitHub workflow or DevOps pipeline that does:
- Builds an image that includes the PR code changes
- Pushes that image to a image repository
- Deploys that image as a new release in your application namespace
- Applies the appropriate Bridge routing labels and annotations 

The only implementation specific to Bridge is applying the routing labels:
```
- name: Add routing labels
      run: |
        kubectl label pods --selector="app=bikes,release=${{steps.generate-release-name.outputs.result}}" routing.visualstudio.io/route-from=bikes -n ${{ secrets.MASTER_SPACE }} --overwrite=true
        kubectl annotate pods --selector="app=bikes,release=${{steps.generate-release-name.outputs.result}}" routing.visualstudio.io/route-on-header=kubernetes-route-as=${{steps.generate-valid-branch-name.outputs.result}} -n ${{ secrets.MASTER_SPACE }} --overwrite=true
```

Even though the below workflow is specific to Azure/AKS, you can use it as a guide to rewrite the equivalent for other Cloud/Kubernetes providers:
[GitHub Actions PR Flow Sample](https://github.com/microsoft/mindaro/blob/master/.github/workflows/bikes.yml)

Please let me know if you have any questions. 
Thank you

**Comment by iSeiryu** [comment]
https://github.com/microsoft/mindaro/projects/1#card-40812958
Looks like other cloud providers are being added right now?

**Comment by daniv-msft** [comment]
@iSeiryu Other cloud providers (AWS' EKS, Google Cloud's GKE, etc.) or even local Kubernetes (minikube) are already available in Bridge to Kubernetes.
However we support non-AKS clusters as preview for now, so please let us know in case you encounter any errors so that we can fix them.

The scenario mentioned by @thalesfsp was in regards to the PR Flow, which is a specific use of Bridge to Kubernetes.

Also, thank you for linking to the project's backlog page: the `Wider support of Kubernetes` was in the wrong column. Fixed it, thanks!

**Comment by k3NGuru** [comment]
Does Visual Studio 2019 support another cloud\on-premises, not AKS?
Visual Studio Code support another provider, but in Visual Studio 2019 i see only AKS

**Comment by daniv-msft** [comment]
@k3NGuru It's not yet available, but it will soon be! The development is making good progress and I expect it should be available in the coming weeks.
+@danegsta for FYI.

**Comment by iSeiryu** [comment]
@daniv-msft wait, in your response to me you said they "are already available in Bridge to Kubernetes.".
But in your response to @k3NGuru you are saying "it's not available yet".
Which one is correct?

**Comment by daniv-msft** [comment]
@iSeiryu It is already available if you're using VS Code, and will be in a couple of weeks if you're using Visual Studio. However, I realize that I didn't mention `in VS Code` previously. Sorry that it was ambiguous.

**Comment by SVronskiy** [comment]
@daniv-msft please keep us informed how are thing are going on! 
May be there's some beta release of VS extension to install/test on vanila on-premises k8s?

**Comment by daniv-msft** [comment]
@SVronskiy Absolutely! I don't believe there is an existing beta program for the VS extension, but @danegsta please let me know if I missed it.
In any case, we expect to release this change around mid-December, so it will come quickly.

**Comment by danegsta** [comment]
@k3NGuru the Visual Studio Bridge to Kubernetes extension was just updated on the [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.mindaro) with support for connecting to clusters from your local kube config

**Comment by k3NGuru** [comment]
> 
> 
> @k3NGuru the Visual Studio Bridge to Kubernetes extension was just updated on the [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.mindaro) with support for connecting to clusters from your local kube config

Yes, we have already updated and are trying to work.
So far problems with setting up isolation routing

**Comment by amsoedal** [comment]
Hi @k3NGuru sorry you're running into issues with the isolation. Are you seeing "Failed to get routing manager status" or other issues? If you grab the logs from your machine (%TEMP%/Bridge to Kubernetes) & from [the routing manager pod](https://github.com/microsoft/mindaro/issues/26#issuecomment-724280014), I can take a look and see if we can get you unblocked!

**Comment by k3NGuru** [comment]
Hi @amsoedal 
We have k8s (1.18) on-promises. Our project based on .net core. When i trying apply Bridge to kubernetes to our dev namespace, doesn't apply URL (i waiting 10+ minutes).
Namespace - epp-dev

![2021-01-07 18_28_55-Edit profile for Bridge to Kubernetes](https://user-images.githubusercontent.com/138567/103888435-52ca0100-5117-11eb-8753-8ed517eb0d6c.png)
[Bridge To Kubernetes.zip](https://github.com/microsoft/mindaro/files/5781362/Bridge.To.Kubernetes.zip)

**Comment by amsoedal** [comment]
@k3NGuru thanks for these details! We will investigate and get back to you on this thread.

**Comment by pragyamehta** [comment]
Hi @k3NGuru  would it be possible for you to send over your ingress yaml to us? I am trying to understand how you have setup your ingress. Please send it over to bridgetokubernetes@microsoft.com with a link to the issue and we will try to get you unblocked asap. Thanks!

**Comment by k3NGuru** [comment]
@pragyamehta sent email from LebedevDO@sibgenco.ru

**Comment by greenie-msft** [comment]
Issue was resolved with the customer over an email. Closing the thread, but feel free to comment if still experiencing this behavior.
