### ISSUE TITLE
Any plants to support a .Net Framework?

### ISSUE THREAD

**Issue by idealist1508** [microsoft/mindaro#72]
**Is your feature request related to a problem? Please describe.** 
Our application runs on .Net Framework 4.7 in AKS and we are looking for a possibility to debug it in cluster.

**Comment by greenie-msft** [comment]
Hi @idealist1508,

Yes, we have plans to support Windows containers which will enable .Net Framework applications to use Bridge to Kubernetes. 

This is a high priority item on our backlog and we hope to address it in the upcoming months. I will make an announcement on our GitHub issues page once this work has been completed. 

Thank you.

**Comment by greenie-msft** [comment]
I wanted to provide an update on this thread. We have further researched this subject and have not found a strong request for supporting .NET Framework. We still have this on our backlog, but it's not a high priority at this time. 

Please feel free to reach out with further questions you might have. Thank you

**Comment by Edu115** [comment]
Ah this is disappointing. After seeing your comments on other threads/demos @greenie-msft I was trying to find on your public roadmap where this was, and couldn't find it. Alas, it seems you have deprioritized it. We have recently moved our website to AKS but parts of the system needed to continue running on Windows k8s nodes for .NET Framework support.

I was quite excited to see Bridge to Kubernetes as a great candidate to improve our development experience, too bad.
