### ISSUE TITLE
Issue with port/targetPort on services

### ISSUE THREAD

**Issue by morganlaneap** [microsoft/mindaro#79]
We are running a service on our cluster with a `port` of 80 and a `targetPort` of 3000. I have configured B2K to point at this service and use local port 3000. No matter what I do, it just does not seem to work, I get time outs, but no console errors or anything else like it.

Is this something you are aware of, or am I just doing something wrong 😛 

I'm running VSCode with a next.js app

**Comment by daniv-msft** [comment]
Thanks for creating this issue, and sorry you run into it.

Does Bridge work for other services on your cluster? Or is this a general issue with Bridge to Kubernetes on your cluster?

Could you please confirm that your Next.js app listens on the port 3000 locally (which might be different from the `targetPort`, depending of your app's configuration)?

Finally, could you please clarify if you're using Bridge isolated or not? If yes, could you please let us know if running it without isolation makes any difference in your case?

**Comment by greenie-msft** [comment]
Closing this thread due to inactivity. @morganlaneap, please feel free to respond and we can reopen the thread. Thank you.
