### ISSUE TITLE
Problem running on AKS with Istio

### ISSUE THREAD

**Issue by Haim-Bi** [microsoft/mindaro#81]
Hi,
I am using AKS with K8s version 1.17.9.
in my cluster i have Istio install according to https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-linux , with no other modifications.

when i am trying to run Bridge on this cluster i am having an error:
![image](https://user-images.githubusercontent.com/65607826/98904086-9ca0bd00-24c1-11eb-9289-5025353ed234.png)

**This error is only when i am trying to isolate the local version from other developers**

Attached log files,
[bridge-library-2020-11-12-06-32-06-2092.txt](https://github.com/microsoft/mindaro/files/5528693/bridge-library-2020-11-12-06-32-06-2092.txt)
[bridge-mindarocli-2020-11-12-06-32-06-2092.txt](https://github.com/microsoft/mindaro/files/5528696/bridge-mindarocli-2020-11-12-06-32-06-2092.txt)

On same cluster setup without Istio, seems to work OK.

Please advise.

**Comment by pragyamehta** [comment]
Hi @Haim-Bi Thanks for opening this issue! It would be great if you could provide logs from your routing manager in your namespace.
You can retrieve the logs by running the below commands :

Retrieve the routing manager pod name
kubectl -n {namespace} get pods
Retrieve logs for the routing manager pod
kubectl -n {namespace} logs {routing manager pod name from step 1} > routing-manager-logs.txt
Kindly send the routing-manager-logs.txt to us and we will investigate and get back to you!

The logs may contain PII, so please feel free to send the logs to bridgetokubernetes@microsoft.com and we'll take a look! Please don't forget to link this issue so that we have the context. Thanks!

**Comment by Haim-Bi** [comment]
@pragyamehta thank you, i sent my logs to the mail you provided.

**Comment by Haim-Bi** [comment]
is this issue related https://github.com/microsoft/mindaro/issues/52 ?
since istio is using sidecar as well

**Comment by pragyamehta** [comment]
Following up further over email. For anyone else reading this post, Bridge to Kubernetes (with isolation disabled) works with service meshes. We have prioritized the support for service mesh with isolation as well on our end. Thanks!

**Comment by irperez** [comment]
@pragyamehta does this include Istio using a Gateway/Virtual Service setup?  To be clear?

**Comment by Haim-Bi** [comment]
> @pragyamehta does this include Istio using a Gateway/Virtual Service setup? To be clear?

Yes,
Using istio-ingressgateway (envoy) as load balancer that route the request according to the gateway with virtual service. (Using istio default profile if that helps)

**Comment by irperez** [comment]
@pragyamehta You all rock!!!!  I was under the impression it was not possible just a couple months ago.

**Comment by mattjbrent** [comment]
any update on the ETA for support for Bridge to Kubernetes in isolation mode with Istio/Service Mesh?

**Comment by daniv-msft** [comment]
Thanks @mattjbrent for your comment. We investigated this scenario a couple of months ago and, unfortunately, isolation with service mesh would actually be quite complex to have and would require a deep understanding of each service mesh we want to support. Would using Bridge non-isolated be a possibility for you, or is impossible in your case?

**Comment by Haim-Bi** [comment]
Since @daniv-msft  answered that currently and in the near future it will not be supported i am closing this issue and work non-isolated. Thank you all.
