### ISSUE TITLE
Patch request FieldValueForbidden

### ISSUE THREAD

**Issue by Creedzy** [microsoft/mindaro#93]
Hi . I am running into an issue running Bridge on AWS EC2 instances. The cluster is created using kops if required I can give you further information. The steps are as follows. 

Prerequisites: 
VS Code on MacOS - [ x ]
Installed Bridge to Kubernetes VS Code extension from the market.  - [ x ] 
Kubernetes cluster with a running service/application - [ x ]

> 3 Nodes 
> Single Helm Release 
> 6-7 Stateful Sets
> 9 Pods, Target pod: microidv ( Spring boot application )

1. Ran the configuration process using (⇧⌘P),
2. Selected the service
3. Entered local port(8080)
4. Selected debug profile 
5. Ran the debug profile (Not in isolation)
6. Allowed EndpointManager to edit hosts file
7.  Connection fails

Output: 
`Patch 'idv/microidv-0/microidv' to use 'bridgetokubernetes.azurecr.io/lpkremoteagent:0.1.4' failed: with error: Operation returned an invalid status code 'UnprocessableEntity'
Stopping workload and cleaning up...`

Extension log: 
`2020-12-15T12:23:27.388Z | Common Extension Root    | ERROR | Error: cli-client-connect-error <stack>Error: Patch 'idv/microidv-0/microidv' to use 'bridgetokubernetes.azurecr.io/lpkremoteagent:0.1.4' failed: with error: Operation returned an invalid status code 'UnprocessableEntity'\n\n    at ChildProcess.<anonymous> (/Users/atanasatanasov/.vscode/extensions/mindaro.mindaro-1.0.120201211/dist/extension.js:3:140460)\n   at ChildProcess.emit (events.js:223:5)\n   at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)</stack>
2020-12-15T12:23:27.391Z | Connect (id-v.micro-idv/ | ERROR | Error: connect-error <stack>Error: Patch 'idv/microidv-0/microidv' to use 'bridgetokubernetes.azurecr.io/lpkremoteagent:0.1.4' failed: with error: Operation returned an invalid status code 'UnprocessableEntity'\n\n        at ChildProcess.<anonymous> (/Users/atanasatanasov/.vscode/extensions/mindaro.mindaro-1.0.120201211/dist/extension.js:3:140460)\n   at ChildProcess.emit (events.js:223:5)\n        at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)</stack>`

kube-apiserver log excerpt: 
**Some parts have been omitted for brevity**
`{
    "level": "RequestResponse",
    "stage": "ResponseComplete",
    "requestURI": "/api/v1/namespaces/idv/pods/microidv-0",
    "verb": "patch",
    "objectRef": {
        "resource": "pods",
        "namespace": "idv",
        "name": "microidv-0",
        "apiVersion": "v1"
    },
    "responseStatus": {
        "metadata": {},
        "status": "Failure",
        "reason": "Invalid",
        "code": 422
    },
    "requestObject": [{
        "value": "bridgetokubernetes.azurecr.io/lpkremoteagent:0.1.4",
        "path": "/spec/containers/0/image",
        "op": "replace"
    }, {
        "value": [{
            "name": "BRIDGE_COLLECT_TELEMETRY",
            "value": "True"
        }, {
            "name": "CONSOLE_VERBOSITY",
            "value": "Verbose"
        }, {
            "name": "BRIDGE_CORRELATION_ID",
            "value": "edab7805-aaca-40f3-8504-06d3dcc4b4c81608033886187:3f466e313f4b:e03959fce20f"
        }],
        "path": "/spec/containers/0/env",
        "op": "replace"
    }],
    "responseObject": {
        "kind": "Status",
        "apiVersion": "v1",
        "metadata": {},
        "status": "Failure",
        "reason": "Invalid",
        "details": {
            "name": "microidv-0",
            "kind": "Pod",
            "causes": [{
                "reason": "FieldValueForbidden",
                "message": "Forbidden: pod updates may not change fields other than
                 `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` 
                 (only additions to existing tolerations)",
                "field": "spec"
            }]
        },
        "code": 422
    }
}`

The value referred to is ` "path": "/spec/containers/0/env",  "op": "replace"`.  I've had a look around and
according to [this](https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/api-reference/v1/definitions.html) env is not updatable and according to [this](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#container-v1-core) the patch strategy can be merge not replace.

Am I missing something less than obvious in my cluster setup or the usage of Bridge for Kubernetes or is it a bug? 

**Environment Details**

Client used: VS Code
Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:46:53.673Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
mindaro-dev.file-downloader@1.0.9
mindaro.mindaro@1.0.120201211

Looking forward to using this, it is an extremely useful tool. 

Thanks.

**Comment by rakeshvanga** [comment]
@Creedzy Thanks for the detailed information and logs. I believe this issue is on our side and to confirm can you share the logs from `$TMPDIR\Bridge To Kubernetes` folder?

Also, can you describe the K8 resources for the service being debugged? Specifically, I would like to know if only `pods` and `services` are part of this service without K8s deployment resource?

**Comment by Creedzy** [comment]
Hi @rakeshvanga 

I have uploaded the log files from `$TMPDIR `

The chart consists of: 
`kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.resourcePrefix }}microidv
spec:
  selector:
    app: {{ .Values.resourcePrefix }}microidv
  ports:
  - protocol: TCP
    name: microidv-http
    port: 8080
    targetPort: 8080`
    
    `apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: microidv
  labels:
    app: microidv
spec:
  serviceName: microidv
  replicas: {{ .Values.numComponents }}
  selector:
    matchLabels:
      app: microidv
  template:
    metadata:
      name: microidv
      labels:
        app: microidv
        component: microidv
    spec:
      containers:
        - name: microidv
          image: "{{ .Values.imageRepository }}/{{ .Values.image }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: {{ .Values.envConfigMapName }}
          resources:
            limits:
              memory: "{{ .Values.global.idvLimitsMemory }}"
            requests:
              memory: "{{ .Values.global.idvRequestsMemory }}"
          volumeMounts:
            - name: app-logs
              mountPath: ...
            - name: tomcat-logs
              mountPath: /usr/local/tomcat/logs
{{if .Values.enableFilebeat}}
        - name: filebeat
          image: "{{ .Values.loggingRepository }}/{{ .Values.loggingImage }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          volumeMounts:
            - name: tomcat-logs
              mountPath: /usr/local/tomcat/logs
            - name: app-logs
              mountPath: /opt/Pirean/A1/logs
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
{{end}}
        ....      `
              
And 2 config maps.
 
I should probably mention that there is a second container (filebeat sidecar) which is currently disabled as per the requirement to have a single container. 

This is a sub-chart, the main chart includes 1 deployment (Apache server). It would look something like this: 

`dependencies:
  - name: apache
    version: ">=1.0.12"
    repository: "@private-repo"
... other dependencies ... 
  - name: microidv
    version: ">=1.0.0"
    repository: "@private-repo"
`

Please let me know if this is not what you asked for. Thanks

[bridge-endpointmanager-2020-12-18-15-32-05-6233.txt](https://github.com/microsoft/mindaro/files/5717031/bridge-endpointmanager-2020-12-18-15-32-05-6233.txt)
[bridge-library-2020-12-18-15-31-55-6224.txt](https://github.com/microsoft/mindaro/files/5717032/bridge-library-2020-12-18-15-31-55-6224.txt)
[bridge-library-2020-12-18-15-32-01-6226.txt](https://github.com/microsoft/mindaro/files/5717033/bridge-library-2020-12-18-15-32-01-6226.txt)
[bridge-mindarocli-2020-12-18-15-31-54-6224.txt](https://github.com/microsoft/mindaro/files/5717034/bridge-mindarocli-2020-12-18-15-31-54-6224.txt)
[bridge-mindarocli-2020-12-18-15-32-00-6226.txt](https://github.com/microsoft/mindaro/files/5717035/bridge-mindarocli-2020-12-18-15-32-00-6226.txt)

**Comment by rakeshvanga** [comment]
@Creedzy Thanks a lot for the detailed k8s resouces and logs. Yes, I can confirm that this is a issue on Bridge To Kubernetes side. I have logged a bug and someone from my team will look into and fix this as soon as possible.

**Comment by Creedzy** [comment]
Hi there. Any news on this issue?

**Comment by rakeshvanga** [comment]
@Creedzy We have planned this for our next sprint. We should support StatefulSet by end of March or early April.
Some one from our team will update this thread once we release this feature.

Thanks!

**Comment by Creedzy** [comment]
@rakeshvanga I read on another comment that statefulset is working now, which I can confirm. The same scenario ran successfully, so Im closing this for you.
