### ISSUE TITLE
AAD Integration in AKS doesn't work with Bridge to Kubernetes in Visual Studio 2019

### ISSUE THREAD

**Issue by TomGeske** [microsoft/mindaro#96]
**Describe the bug**
When configuring Bridge to Kubernetes profile in Visual Studio 2019 it seems like AKS-managed Azure AD AKS clusters aren’t supported.
 
**To Reproduce**
Steps to follow to reproduce this issue.
1.  Create or use a [AKS-managed AAD cluster](https://docs.microsoft.com/en-us/azure/aks/managed-aad)
2. Ensure you downloaded Azure AD credentials for your cluster
3. Open your project of preference in Visual Studio 2019
4. Select Bridge to Kubernetes Profile
5. Select your existing local Kube Config with OID credentials
6. Namespace shows "Error!" "User: $clusterName$ does not have appropriate auth credentials in kubeconfig"

![image](https://user-images.githubusercontent.com/3658893/102712384-3d547a80-42c1-11eb-8c40-58b2e5bbb0bf.png)

 
**Expected behavior**
k8s namespaces are loaded even with OID / Azure AD credentials.
 
**Logs**
Attach logs from the following directory:
For Windows: %TEMP%/Bridge to Kubernetes [bridge-library-2020-12-20-11-34-00-18556.txt](https://github.com/microsoft/mindaro/files/5720858/bridge-library-2020-12-20-11-34-00-18556.txt)
 
**Environment Details**
Client used Visual Studio:
Client's version: Microsoft Visual Studio Enterprise 2019, Version 16.8.3
Operating System: Windows 10.0.19042

**Comment by pragyamehta** [comment]
Hi @TomGeske thanks for reaching out to us! We are aware of this issue and are working to provide a fix. Meanwhile, please refer to this #26 to get unblocked.
